with keys as (
  select
    'alcohol'::text as alcohol,
    'chilli'::text as chilli,
    'dairy'::text as dairy,
    'dairy-free'::text as dairy_free,
    'egg'::text as egg,
    'fish'::text as fish,
    'garlic'::text as garlic,
    'gluten'::text as gluten,
    'gluten-free'::text as gluten_free,
    'legumes'::text as legumes,
    'low-fodmap'::text as low_fodmap,
    'meat'::text as meat,
    'nuts'::text as nuts,
    'onion'::text as onion,
    'peanut'::text as peanut,
    'pescatarian'::text as pescatarian,
    'poultry'::text as poultry,
    'shellfish'::text as shellfish,
    'soy'::text as soy,
    'vegan'::text as vegan,
    'vegetarian'::text as vegetarian,
    'wheat'::text as wheat
),
upsert_groups as (
  insert into "ingredient_group" ("key", "label", "description")
  select groups."key", groups."label", groups."description"
  from keys
  cross join lateral (
    values
      (keys.meat, 'Meat', 'beef, pork, lamb'),
      (keys.poultry, 'Poultry', 'chicken, turkey'),
      (keys.fish, 'Fish', 'salmon, tuna'),
      (keys.shellfish, 'Shellfish', 'prawns, mussels'),
      (keys.dairy, 'Dairy', 'milk, cheese'),
      (keys.egg, 'Egg', 'egg and egg yolk'),
      (keys.gluten, 'Gluten', 'wheat, barley, rye'),
      (keys.wheat, 'Wheat', 'wheat flour, pasta'),
      (keys.legumes, 'Legumes', 'beans, lentils'),
      (keys.nuts, 'Tree nuts', 'almond, cashew'),
      (keys.peanut, 'Peanut', 'peanut products'),
      (keys.soy, 'Soy', 'soy sauce, tofu'),
      (keys.onion, 'Onion', 'onions, shallots'),
      (keys.garlic, 'Garlic', 'garlic, granules'),
      (keys.chilli, 'Chilli', 'fresh or dried'),
      (keys.alcohol, 'Alcohol', 'wine, beer, spirits')
  ) as groups("key", "label", "description")
  on conflict ("key") do update set
    "label" = excluded."label",
    "description" = excluded."description",
    "updated_at" = now()
  returning "key"
),
upsert_presets as (
  insert into "diet_preset" ("key", "label", "description")
  select presets."key", presets."label", presets."description"
  from keys
  cross join lateral (
    values
      (keys.vegetarian, 'Vegetarian', 'no meat or fish'),
      (keys.vegan, 'Vegan', 'no animal products'),
      (keys.pescatarian, 'Pescatarian', 'no meat, fish ok'),
      (keys.dairy_free, 'Dairy-free', 'no milk or cheese'),
      (keys.gluten_free, 'Gluten-free', 'no wheat or gluten'),
      (keys.low_fodmap, 'Low-FODMAP review', 'flag common triggers')
  ) as presets("key", "label", "description")
  on conflict ("key") do update set
    "label" = excluded."label",
    "description" = excluded."description",
    "updated_at" = now()
  returning "key"
)
insert into "diet_preset_excluded_group" ("preset_key", "group_key")
select exclusions.preset_key, exclusions.group_key
from keys
cross join lateral (
  values
    (keys.vegetarian, keys.meat),
    (keys.vegetarian, keys.poultry),
    (keys.vegetarian, keys.fish),
    (keys.vegetarian, keys.shellfish),
    (keys.vegan, keys.meat),
    (keys.vegan, keys.poultry),
    (keys.vegan, keys.fish),
    (keys.vegan, keys.shellfish),
    (keys.vegan, keys.dairy),
    (keys.vegan, keys.egg),
    (keys.pescatarian, keys.meat),
    (keys.pescatarian, keys.poultry),
    (keys.dairy_free, keys.dairy),
    (keys.gluten_free, keys.gluten),
    (keys.low_fodmap, keys.onion),
    (keys.low_fodmap, keys.garlic),
    (keys.low_fodmap, keys.wheat),
    (keys.low_fodmap, keys.legumes)
) as exclusions(preset_key, group_key)
inner join upsert_presets on upsert_presets."key" = exclusions.preset_key
inner join upsert_groups on upsert_groups."key" = exclusions.group_key
on conflict ("preset_key", "group_key") do nothing;
--> statement-breakpoint
insert into "ingredient" ("slug", "name", "category")
values
  ('chicken-breast', 'chicken breast', 'protein'),
  ('turkey-mince', 'turkey mince', 'protein'),
  ('chorizo', 'chorizo', 'protein'),
  ('bacon', 'bacon', 'protein'),
  ('pork-sausage', 'pork sausage', 'protein'),
  ('eggs', 'eggs', 'protein'),
  ('white-onion', 'white onion', 'vegetable'),
  ('red-onion', 'red onion', 'vegetable'),
  ('onion', 'onion', 'vegetable'),
  ('bell-pepper', 'bell pepper', 'vegetable'),
  ('red-pepper', 'red pepper', 'vegetable'),
  ('garlic', 'garlic', 'vegetable'),
  ('peas', 'peas', 'vegetable'),
  ('chopped-tomatoes', 'chopped tomatoes', 'vegetable'),
  ('tomato-passata', 'tomato passata', 'vegetable'),
  ('frozen-vegetables', 'frozen vegetables', 'vegetable'),
  ('fresh-tomatoes', 'fresh tomatoes', 'vegetable'),
  ('garlic-puree', 'garlic puree', 'vegetable'),
  ('tomato-puree', 'tomato puree', 'vegetable'),
  ('frozen-peas', 'frozen peas', 'vegetable'),
  ('frozen-peppers', 'frozen peppers', 'vegetable'),
  ('spinach', 'spinach', 'vegetable'),
  ('vine-tomato', 'vine tomato', 'vegetable'),
  ('spring-onion', 'spring onion', 'vegetable'),
  ('leek', 'leek', 'vegetable'),
  ('potato', 'potato', 'vegetable'),
  ('cherry-tomato', 'cherry tomato', 'vegetable'),
  ('carrot', 'carrot', 'vegetable'),
  ('sweet-potato', 'sweet potato', 'vegetable'),
  ('lettuce', 'lettuce', 'vegetable'),
  ('mixed-beans', 'mixed beans', 'legume'),
  ('chickpeas', 'chickpeas', 'legume'),
  ('red-lentils', 'red lentils', 'legume'),
  ('avocado', 'avocado', 'fruit'),
  ('lime', 'lime', 'fruit'),
  ('butter', 'butter', 'dairy'),
  ('unsalted-butter', 'unsalted butter', 'dairy'),
  ('double-cream', 'double cream', 'dairy'),
  ('single-cream', 'single cream', 'dairy'),
  ('creme-fraiche', 'creme fraiche', 'dairy'),
  ('mascarpone', 'mascarpone', 'dairy'),
  ('milk', 'milk', 'dairy'),
  ('cheddar-cheese', 'cheddar cheese', 'dairy'),
  ('parmesan', 'parmesan', 'dairy'),
  ('grana-padano', 'grana padano', 'dairy'),
  ('cream-cheese', 'cream cheese', 'dairy'),
  ('light-soft-cheese', 'light soft cheese', 'dairy'),
  ('mozzarella', 'mozzarella', 'dairy'),
  ('rice', 'rice', 'grain'),
  ('arborio-rice', 'arborio rice', 'grain'),
  ('macaroni', 'macaroni', 'grain'),
  ('penne-pasta', 'penne pasta', 'grain'),
  ('large-pasta-shells', 'large pasta shells', 'grain'),
  ('pasta', 'pasta', 'grain'),
  ('long-grain-rice', 'long grain rice', 'grain'),
  ('paella-rice', 'paella rice', 'grain'),
  ('tortilla-wrap', 'tortilla wrap', 'grain'),
  ('farfalle', 'farfalle', 'grain'),
  ('plain-flour', 'plain flour', 'grain'),
  ('bread-flour', 'bread flour', 'grain'),
  ('cornflour', 'cornflour', 'grain'),
  ('semolina', 'semolina', 'grain'),
  ('bread', 'bread', 'grain'),
  ('noodles', 'noodles', 'grain'),
  ('bap', 'bap', 'grain'),
  ('rolled-oats', 'rolled oats', 'grain'),
  ('fresh-basil', 'fresh basil', 'herb'),
  ('fresh-rosemary', 'fresh rosemary', 'herb'),
  ('fresh-parsley', 'fresh parsley', 'herb'),
  ('fresh-coriander', 'fresh coriander', 'herb'),
  ('oregano', 'oregano', 'herb'),
  ('thyme', 'thyme', 'herb'),
  ('italian-herbs', 'italian herbs', 'herb'),
  ('curry-powder', 'curry powder', 'spice'),
  ('hot-chilli-powder', 'hot chilli powder', 'spice'),
  ('ground-coriander', 'ground coriander', 'spice'),
  ('cayenne-pepper', 'cayenne pepper', 'spice'),
  ('paprika', 'paprika', 'spice'),
  ('smoked-paprika', 'smoked paprika', 'spice'),
  ('chilli', 'chilli', 'spice'),
  ('chilli-flakes', 'chilli flakes', 'spice'),
  ('tikka-curry-powder', 'tikka curry powder', 'spice'),
  ('italian-seasoning', 'italian seasoning', 'spice'),
  ('red-chilli-powder', 'red chilli powder', 'spice'),
  ('salt', 'salt', 'spice'),
  ('sea-salt', 'sea salt', 'spice'),
  ('black-pepper', 'black pepper', 'spice'),
  ('peri-peri-salt', 'peri peri salt', 'spice'),
  ('cajun-seasoning', 'cajun seasoning', 'spice'),
  ('taco-seasoning', 'taco seasoning', 'spice'),
  ('msg', 'MSG', 'spice'),
  ('five-spice', 'five spice', 'spice'),
  ('white-pepper', 'white pepper', 'spice'),
  ('dried-parsley', 'dried parsley', 'herb'),
  ('turmeric', 'turmeric', 'spice'),
  ('saffron', 'saffron', 'spice'),
  ('cumin', 'cumin', 'spice'),
  ('garlic-granules', 'garlic granules', 'spice'),
  ('garlic-powder', 'garlic powder', 'spice'),
  ('onion-salt', 'onion salt', 'spice'),
  ('fajita-and-taco-mix', 'fajita and taco mix', 'spice'),
  ('chilli-powder', 'chilli powder', 'spice'),
  ('ginger', 'ginger', 'spice'),
  ('avocado-topping', 'avocado topping', 'spice'),
  ('basil-pesto', 'basil pesto', 'condiment'),
  ('soy-sauce', 'soy sauce', 'condiment'),
  ('lime-juice', 'lime juice', 'condiment'),
  ('peanut-butter', 'peanut butter', 'condiment'),
  ('honey', 'honey', 'condiment'),
  ('sweet-chilli-sauce', 'sweet chilli sauce', 'condiment'),
  ('chipotle-paste', 'chipotle paste', 'condiment'),
  ('mayonnaise', 'mayonnaise', 'condiment'),
  ('guacamole-mix', 'guacamole mix', 'condiment'),
  ('sun-dried-tomato-pesto', 'sun-dried tomato pesto', 'condiment'),
  ('hoisin-sauce', 'hoisin sauce', 'condiment'),
  ('dark-soy-sauce', 'dark soy sauce', 'condiment'),
  ('light-soy-sauce', 'light soy sauce', 'condiment'),
  ('rice-wine-vinegar', 'rice wine vinegar', 'condiment'),
  ('peri-peri-sauce', 'peri peri sauce', 'condiment'),
  ('harissa-paste', 'harissa paste', 'condiment'),
  ('ballymaloe-relish', 'ballymaloe relish', 'condiment'),
  ('sugar', 'sugar', 'sweets'),
  ('brown-sugar', 'brown sugar', 'sweets'),
  ('icing-sugar', 'icing sugar', 'sweets'),
  ('milk-chocolate', 'milk chocolate', 'sweets'),
  ('dark-chocolate', 'dark chocolate', 'sweets'),
  ('caramel', 'caramel', 'sweets'),
  ('dulce-de-leche', 'dulce de leche', 'sweets'),
  ('vegetable-oil', 'vegetable oil', 'oil-fat'),
  ('olive-oil', 'olive oil', 'oil-fat'),
  ('extra-virgin-olive-oil', 'extra virgin olive oil', 'oil-fat'),
  ('coconut-milk', 'coconut milk', 'oil-fat'),
  ('margarine', 'margarine', 'oil-fat'),
  ('chicken-stock', 'chicken stock', 'liquid'),
  ('vegetable-stock', 'vegetable stock', 'liquid'),
  ('pasta-water', 'pasta water', 'liquid'),
  ('white-wine', 'white wine', 'liquid'),
  ('water', 'water', 'liquid'),
  ('orange-juice', 'orange juice', 'liquid'),
  ('dry-yeast', 'dry yeast', 'other'),
  ('prawn-crackers', 'prawn crackers', 'other'),
  ('garlic-bread', 'garlic bread', 'other'),
  ('chips', 'chips', 'other'),
  ('potato-wedges', 'potato wedges', 'other'),
  ('self-raising-flour', 'self-raising flour', 'other'),
  ('caster-sugar', 'caster sugar', 'sweets'),
  ('flour', 'flour', 'other'),
  ('cornflakes', 'cornflakes', 'other'),
  ('cashew-nuts', 'cashew nuts', 'other'),
  ('cashews', 'cashews', 'other'),
  ('ground-almonds', 'ground almonds', 'other'),
  ('naan', 'naan', 'other'),
  ('white-chocolate', 'white chocolate', 'sweets'),
  ('white-chocolate-chips', 'white chocolate chips', 'sweets'),
  ('chicken-stock-pot', 'chicken stock pot', 'other'),
  ('coconut-oil', 'coconut oil', 'other'),
  ('sesame-seeds', 'sesame seeds', 'other'),
  ('ginger-paste', 'ginger paste', 'other'),
  ('salad', 'salad', 'other'),
  ('thai-crackers', 'Thai crackers', 'other'),
  ('chinese-five-spice', 'Chinese five spice', 'spice'),
  ('almond-milk', 'almond milk', 'liquid'),
  ('baby-tomatoes', 'baby tomatoes', 'vegetable'),
  ('beansprouts', 'beansprouts', 'vegetable'),
  ('cucumber', 'cucumber', 'vegetable'),
  ('shallots', 'shallots', 'vegetable'),
  ('sun-dried-tomato', 'sun-dried tomato', 'vegetable'),
  ('sweet-peppers', 'sweet peppers', 'vegetable'),
  ('tomato', 'tomato', 'vegetable'),
  ('buttermilk', 'buttermilk', 'dairy'),
  ('cheese', 'cheese', 'dairy'),
  ('coconut-cream', 'coconut cream', 'oil-fat'),
  ('greek-yoghurt', 'Greek yoghurt', 'dairy'),
  ('light-cream-cheese', 'light cream cheese', 'dairy'),
  ('yoghurt', 'yoghurt', 'dairy'),
  ('baps', 'baps', 'grain'),
  ('basmati-rice', 'basmati rice', 'grain'),
  ('orzo', 'orzo', 'grain'),
  ('pita', 'pita', 'grain'),
  ('spaghetti', 'spaghetti', 'grain'),
  ('dried-oregano', 'dried oregano', 'spice'),
  ('basil', 'basil', 'herb'),
  ('basil-leaves', 'basil leaves', 'herb'),
  ('coriander', 'coriander', 'herb'),
  ('dried-rosemary', 'dried rosemary', 'herb'),
  ('dried-thyme', 'dried thyme', 'herb'),
  ('herbes-de-provence', 'herbes de provence', 'herb'),
  ('cajun-powder', 'cajun powder', 'spice'),
  ('chili-powder', 'chili powder', 'spice'),
  ('garam-masala', 'garam masala', 'spice'),
  ('ground-cumin', 'ground cumin', 'spice'),
  ('kosher-salt', 'kosher salt', 'spice'),
  ('mustard-powder', 'mustard powder', 'spice'),
  ('onion-powder', 'onion powder', 'spice'),
  ('pepper', 'pepper', 'spice'),
  ('sweet-paprika', 'sweet paprika', 'spice'),
  ('mexican-seasoning', 'mexican seasoning', 'spice'),
  ('balsamic-vinegar', 'balsamic vinegar', 'condiment'),
  ('chilli-mayo', 'chilli mayo', 'condiment'),
  ('crunchy-peanut-butter', 'crunchy peanut butter', 'condiment'),
  ('ginger-puree', 'ginger puree', 'condiment'),
  ('lemon-juice', 'lemon juice', 'condiment'),
  ('red-curry-paste', 'red curry paste', 'condiment'),
  ('sriracha', 'sriracha', 'condiment'),
  ('white-wine-vinegar', 'white wine vinegar', 'condiment'),
  ('light-brown-sugar', 'light brown sugar', 'sweets'),
  ('sesame-oil', 'sesame oil', 'oil-fat'),
  ('chicken-thigh', 'chicken thigh', 'protein'),
  ('frozen-raspberries', 'frozen raspberries', 'fruit')
on conflict ("slug") do update set
  "name" = excluded."name",
  "category" = excluded."category",
  "updated_at" = now();
--> statement-breakpoint
insert into "ingredient_group_member" ("group_key", "ingredient_slug")
values
  ('alcohol', 'white-wine'),
  ('chilli', 'hot-chilli-powder'),
  ('chilli', 'cayenne-pepper'),
  ('chilli', 'chilli'),
  ('chilli', 'chilli-flakes'),
  ('chilli', 'red-chilli-powder'),
  ('chilli', 'chilli-powder'),
  ('chilli', 'chili-powder'),
  ('chilli', 'sweet-chilli-sauce'),
  ('chilli', 'chilli-mayo'),
  ('chilli', 'sriracha'),
  ('chilli', 'red-curry-paste'),
  ('egg', 'eggs'),
  ('egg', 'mayonnaise'),
  ('egg', 'chilli-mayo'),
  ('garlic', 'garlic'),
  ('garlic', 'garlic-puree'),
  ('garlic', 'garlic-granules'),
  ('garlic', 'garlic-powder'),
  ('garlic', 'garlic-bread'),
  ('gluten', 'macaroni'),
  ('gluten', 'penne-pasta'),
  ('gluten', 'large-pasta-shells'),
  ('gluten', 'pasta'),
  ('gluten', 'tortilla-wrap'),
  ('gluten', 'farfalle'),
  ('gluten', 'plain-flour'),
  ('gluten', 'bread-flour'),
  ('gluten', 'semolina'),
  ('gluten', 'bread'),
  ('gluten', 'noodles'),
  ('gluten', 'bap'),
  ('gluten', 'garlic-bread'),
  ('gluten', 'self-raising-flour'),
  ('gluten', 'flour'),
  ('gluten', 'naan'),
  ('gluten', 'baps'),
  ('gluten', 'orzo'),
  ('gluten', 'pita'),
  ('gluten', 'spaghetti'),
  ('meat', 'chorizo'),
  ('meat', 'bacon'),
  ('meat', 'pork-sausage'),
  ('nuts', 'cashew-nuts'),
  ('nuts', 'cashews'),
  ('nuts', 'ground-almonds'),
  ('nuts', 'almond-milk'),
  ('onion', 'white-onion'),
  ('onion', 'red-onion'),
  ('onion', 'onion'),
  ('onion', 'spring-onion'),
  ('onion', 'shallots'),
  ('onion', 'onion-salt'),
  ('onion', 'onion-powder'),
  ('peanut', 'peanut-butter'),
  ('peanut', 'crunchy-peanut-butter'),
  ('poultry', 'chicken-breast'),
  ('poultry', 'turkey-mince'),
  ('poultry', 'chicken-thigh'),
  ('poultry', 'chicken-stock'),
  ('poultry', 'chicken-stock-pot'),
  ('shellfish', 'prawn-crackers'),
  ('soy', 'soy-sauce'),
  ('soy', 'dark-soy-sauce'),
  ('soy', 'light-soy-sauce'),
  ('wheat', 'macaroni'),
  ('wheat', 'penne-pasta'),
  ('wheat', 'large-pasta-shells'),
  ('wheat', 'pasta'),
  ('wheat', 'tortilla-wrap'),
  ('wheat', 'farfalle'),
  ('wheat', 'plain-flour'),
  ('wheat', 'bread-flour'),
  ('wheat', 'semolina'),
  ('wheat', 'bread'),
  ('wheat', 'noodles'),
  ('wheat', 'bap'),
  ('wheat', 'garlic-bread'),
  ('wheat', 'self-raising-flour'),
  ('wheat', 'flour'),
  ('wheat', 'naan'),
  ('wheat', 'baps'),
  ('wheat', 'orzo'),
  ('wheat', 'pita'),
  ('wheat', 'spaghetti'),
  ('dairy', 'butter'),
  ('dairy', 'unsalted-butter'),
  ('dairy', 'double-cream'),
  ('dairy', 'single-cream'),
  ('dairy', 'creme-fraiche'),
  ('dairy', 'mascarpone'),
  ('dairy', 'milk'),
  ('dairy', 'cheddar-cheese'),
  ('dairy', 'parmesan'),
  ('dairy', 'grana-padano'),
  ('dairy', 'cream-cheese'),
  ('dairy', 'light-soft-cheese'),
  ('dairy', 'mozzarella'),
  ('dairy', 'buttermilk'),
  ('dairy', 'cheese'),
  ('dairy', 'greek-yoghurt'),
  ('dairy', 'light-cream-cheese'),
  ('dairy', 'yoghurt'),
  ('dairy', 'milk-chocolate'),
  ('dairy', 'white-chocolate'),
  ('dairy', 'white-chocolate-chips'),
  ('legumes', 'mixed-beans'),
  ('legumes', 'chickpeas'),
  ('legumes', 'red-lentils')
on conflict ("group_key", "ingredient_slug") do nothing;
--> statement-breakpoint
insert into "diet_preset_excluded_ingredient" ("preset_key", "ingredient_slug")
values
  ('vegan', 'honey')
on conflict ("preset_key", "ingredient_slug") do nothing;
