# CodeRabbit Configuration
# Reference: https://docs.coderabbit.ai/reference/configuration

# =============================================================================
# GLOBAL SETTINGS
# =============================================================================

language: "en-GB"
tone_instructions: ""
early_access: false
enable_free_tier: true

# =============================================================================
# REVIEWS
# =============================================================================

reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  high_level_summary_placeholder: "@coderabbitai summary"
  high_level_summary_in_walkthrough: false
  auto_title_placeholder: "@coderabbitai"
  auto_title_instructions: ""
  review_status: true
  commit_status: true
  fail_commit_status: false
  collapse_walkthrough: true
  changed_files_summary: true
  sequence_diagrams: true
  estimate_code_review_effort: false
  assess_linked_issues: true
  related_issues: true
  related_prs: true
  suggested_labels: true
  auto_apply_labels: false
  suggested_reviewers: false
  auto_assign_reviewers: false
  in_progress_fortune: false
  poem: false
  labeling_instructions: []
  path_filters: []
  path_instructions: []
  abort_on_close: true
  disable_cache: false

  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords: []
    labels: []
    drafts: false
    base_branches: []
    ignore_usernames: []

  finishing_touches:
    docstrings:
      enabled: false
    unit_tests:
      enabled: true

  pre_merge_checks:
    docstrings:
      mode: "off"
      threshold: 0
    title:
      mode: "off"
      requirements: ""
    description:
      mode: "off"
    issue_assessment:
      mode: "warning"
    custom_checks: []

  tools:
    # AST-based code analysis
    ast-grep:
      rule_dirs: []
      util_dirs: []
      essential_rules: true
      packages: []

    # Shell script linting
    shellcheck:
      enabled: true

    # Markdown linting
    markdownlint:
      enabled: true

    # GitHub Checks integration
    github-checks:
      enabled: true
      timeout_ms: 90000

    # Grammar and style checking
    languagetool:
      enabled: true
      enabled_rules: []
      disabled_rules: []
      enabled_categories: []
      disabled_categories: []
      enabled_only: false
      level: "default"

    # JavaScript/TypeScript linter and formatter
    biome:
      enabled: true

    # Dockerfile linting
    hadolint:
      enabled: true

    # YAML file linting
    yamllint:
      enabled: true

    # Secret scanning
    gitleaks:
      enabled: true

    # Infrastructure-as-code security
    checkov:
      enabled: true

    # Generic security and code quality scanner
    semgrep:
      enabled: true
      config_file: ""

    # GitHub Actions workflow linting
    actionlint:
      enabled: true

    # SQL linting
    sqlfluff:
      enabled: true

    # .env file linting
    dotenvLint:
      enabled: true

    # HTML linting
    htmlhint:
      enabled: true

    # Package vulnerability scanning
    osvScanner:
      enabled: true

    # Disabled language-specific linters (languages not used in this project)
    # Python linters
    ruff:
      enabled: false
    pylint:
      enabled: false
    flake8:
      enabled: false

    # Ruby linters
    rubocop:
      enabled: false

    # Go linters
    golangci-lint:
      enabled: false

    # Kotlin linters
    detekt:
      enabled: false

    # PHP linters
    phpstan:
      enabled: false
    phpmd:
      enabled: false
    phpcs:
      enabled: false

    # Java/multi-language linters
    pmd:
      enabled: false

    # ESLint (using Biome instead)
    eslint:
      enabled: false

# =============================================================================
# CHAT
# =============================================================================

chat:
  art: true
  auto_reply: true
  integrations:
    jira:
      usage: "auto"
    linear:
      usage: "auto"

# =============================================================================
# KNOWLEDGE BASE
# =============================================================================

knowledge_base:
  opt_out: false
  web_search:
    enabled: true
  code_guidelines:
    enabled: true
    filePatterns: []
  learnings:
    scope: "auto"
  issues:
    scope: "auto"
  jira:
    usage: "auto"
    project_keys: []
  linear:
    usage: "auto"
    team_keys: []
  pull_requests:
    scope: "auto"
  mcp:
    usage: "auto"
    disabled_servers: []

# =============================================================================
# CODE GENERATION
# =============================================================================

code_generation:
  docstrings:
    language: "en-GB"
    path_instructions: []
  unit_tests:
    path_instructions: []
