apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: t3-code-cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: t3-code-cache-local
  volumeMode: Filesystem
  volumeName: t3-code-remote-development-cache
