stages:
  prepare:
    cmd: pnpm exec tsx src/stages/prepare.ts
    deps:
      - data/ground-truth.json
      - data/recipe-images
      - src/stages/prepare.ts
      - src/schemas/ground-truth.ts
      - src/lib/io.ts
    outs:
      - outputs/prepared.json

  infer:
    cmd: pnpm exec tsx src/stages/infer.ts
    deps:
      - outputs/prepared.json
      - data/recipe-images
      - src/stages/infer.ts
      - src/lib/infer-retry.ts
      - src/lib/openrouter.ts
      - src/lib/images.ts
      - src/lib/env.ts
      - src/lib/recipe-output.ts
      - src/schemas/ground-truth.ts
      - src/lib/io.ts
    outs:
      - outputs/predictions.json
      - outputs/infer-failures.json

  normalize:
    cmd: pnpm exec tsx src/stages/normalize.ts
    deps:
      - outputs/predictions.json
      - src/stages/normalize.ts
      - src/lib/ingredient-normalization.ts
      - src/lib/io.ts
      - src/schemas/ground-truth.ts
      - outputs/prepared.json
    outs:
      - outputs/predictions-normalized.json
      - outputs/normalization-decisions.json

  evaluate:
    cmd: pnpm exec tsx src/stages/evaluate.ts
    deps:
      - outputs/prepared.json
      - outputs/predictions-normalized.json
      - src/stages/evaluate.ts
      - src/evaluation/metrics.ts
      - src/lib/io.ts
    metrics:
      - outputs/metrics.json
    plots:
      - outputs/per-image-scores.json
