stages:
  prepare:
    cmd: pnpm exec tsx src/stages/prepare.ts
    deps:
      - data/ground-truth.json
      - data/recipe-images
      - src/stages/prepare.ts
      - src/schemas/ground-truth.ts
      - src/lib/io.ts
    outs:
      - outputs/prepared.json

  parse:
    cmd: pnpm exec tsx src/stages/parse.ts
    deps:
      - outputs/prepared.json
      - data/recipe-images
      - src/stages/parse.ts
      - src/lib/parse-retry.ts
      - src/lib/openrouter.ts
      - src/lib/images.ts
      - src/lib/env.ts
      - src/lib/image-key.ts
      - src/lib/recipe-output.ts
      - src/schemas/ground-truth.ts
      - src/schemas/parse-failures.ts
      - src/lib/io.ts
    outs:
      - outputs/predictions.json
      - outputs/parse-failures.json

  evaluate_extraction:
    cmd: pnpm exec tsx src/stages/evaluate-extraction.ts
    deps:
      - outputs/prepared.json
      - outputs/predictions.json
      - src/stages/evaluate-extraction.ts
      - src/evaluation/metrics.ts
      - src/lib/image-key.ts
      - src/lib/io.ts
    outs:
      - outputs/extraction-metrics.json
      - outputs/extraction-per-image-scores.json

  canonicalize:
    cmd: pnpm exec tsx src/stages/canonicalize.ts
    deps:
      - outputs/predictions.json
      - data/canonical-ingredients.json
      - src/stages/canonicalize.ts
      - src/lib/ingredient-canonicalization.ts
      - src/lib/io.ts
      - src/schemas/ground-truth.ts
      - src/schemas/canonical-ingredients.ts
    outs:
      - outputs/predictions-canonicalized.json
      - outputs/canonicalization-decisions.json

  evaluate:
    cmd: pnpm exec tsx src/stages/evaluate.ts
    deps:
      - outputs/prepared.json
      - outputs/predictions-canonicalized.json
      - src/stages/evaluate.ts
      - src/evaluation/metrics.ts
      - src/lib/image-key.ts
      - src/lib/io.ts
    metrics:
      - outputs/metrics.json
    plots:
      - outputs/per-image-scores.json
