all:
  vars:
    ansible_user: robbie
  hosts:
    mac-mini:
      ansible_host: robbies-mac-mini.tailaa0e46.ts.net
      ansible_connection: local
    raspberry-pi:
      ansible_host: raspberrypi.tailaa0e46.ts.net
      ansible_user: pi
      host_required_commands:
        - lpstat
    asus-desktop:
      ansible_host: asus-desktop.tailaa0e46.ts.net
      ansible_python_interpreter: /run/current-system/sw/bin/python3
  children:
    always_on:
      hosts:
        mac-mini:
        raspberry-pi:
    dns_resolvers:
      hosts:
        mac-mini:
        raspberry-pi:
    compute_workers:
      hosts:
        asus-desktop:
    macos_hosts:
      hosts:
        mac-mini:
    linux_hosts:
      hosts:
        raspberry-pi:
        asus-desktop:
    nixos_hosts:
      hosts:
        asus-desktop:
    k3s_servers:
      hosts: {}
    k3s_agents:
      hosts: {}
