import type { AccountContent } from "@/lib/domain/assettracker/account";

export const accounts: AccountContent[] = [
  {
    id: "marcus-savings",
    name: "Marcus Savings",
    provider: "Goldman Sachs",
    currency: "GBP",
    createdAt: "2021-03-15",
    assetType: "cash",
    expectedAnnualReturn: 0.045,
  },
  {
    id: "vanguard-global-all-cap",
    name: "Vanguard Global All Cap",
    provider: "Vanguard",
    currency: "GBP",
    createdAt: "2020-06-01",
    assetType: "stocks",
    expectedAnnualReturn: 0.08,
  },
  {
    id: "trading-212-isa",
    name: "Trading 212 ISA",
    provider: "Trading 212",
    currency: "GBP",
    createdAt: "2022-01-10",
    assetType: "stocks",
    expectedAnnualReturn: 0.07,
  },
  {
    id: "coinbase-btc",
    name: "Coinbase BTC",
    provider: "Coinbase",
    currency: "GBP",
    createdAt: "2021-11-01",
    assetType: "crypto",
    expectedAnnualReturn: 0.15,
  },
  {
    id: "nationwide-current",
    name: "Nationwide Current",
    provider: "Nationwide",
    currency: "GBP",
    createdAt: "2019-01-01",
    assetType: "cash",
    expectedAnnualReturn: 0.01,
  },
  {
    id: "old-mutual-pension",
    name: "Old Mutual Pension",
    provider: "Old Mutual",
    currency: "GBP",
    createdAt: "2018-09-01",
    closedAt: "2023-06-30",
    assetType: "stocks",
    expectedAnnualReturn: 0.06,
  },
];
