apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: t3-code-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 90Gi
  storageClassName: t3-code-local
  volumeMode: Filesystem
