apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - ../../base/media
  - persistent-volumes.yaml
labels:
  - pairs:
      homelab.dev/environment: home
    includeSelectors: false
    includeTemplates: true
