import type { JobRoleContent } from "@/lib/domain/role/jobRole";

export const experiences: JobRoleContent[] = [
  {
    company: "Terminal Industries",
    companyUrl: "https://terminal-industries.com/",
    logoPath: "/company-logos/terminal-industries.png",
    title: "Principal Software Engineer",
    location: "Belfast, UK",
    startDate: "2024-05",
    description:
      "Building real-time computer vision products and ML pipelines, while driving engineering practices for a startup transitioning from pre-product to production.",
    responsibilities: [
      "Built real-time computer vision products for multi-stream video and image analysis, for identifier identification in complex environments",
      "Engineered ML pipelines with data version control, benchmarking infrastructure, and end-to-end observability powered by Grafana Cloud (Prometheus, Loki, Tempo)",
      "Developed web services, Terraform managed infrastructure, and LLM-powered document analysis solutions",
      "Built internal tools in TypeScript and React, and contributed to API servers in Go",
      "Project managed cross-functional teams and drove agile development practices that accelerated time-to-market",
      "Was pivotal in transitioning from pre-product to production, delivering the MVP to market and establishing lean engineering practices for rapid iteration",
    ],
    technologies: [
      "Python",
      "Terraform",
      "Grafana",
      "Prometheus",
      "DVC",
      "Google Gemini",
      "TypeScript",
      "GitHub Actions",
      "TensorRT",
      "Go",
      "AWS",
      "OpenRouter",
      "Cloudflare Workers",
      "Leaflet",
    ],
  },
  {
    company: "Bestomer",
    companyUrl: "https://bestomer.com/",
    logoPath: "/company-logos/bestomer.png",
    title: "Machine Learning Lead",
    location: "Remote, UK",
    startDate: "2023-05",
    endDate: "2024-02",
    description:
      "Led ML strategy at a seed-stage startup, building pipelines, evaluating build-vs-buy decisions, and developing full-stack prototypes.",
    responsibilities: [
      "Led ML strategy and built end-to-end ML pipelines for training, evaluation, and deployment",
      "Optimized, evaluated, and integrated ML models powering semantic search, image similarity search, invoice extraction, product detection, and RAG-based chatbots",
      "Developed backend services in Python and TypeScript and contributed to iOS application development",
      "Assessed third-party services to inform build-vs-buy decisions through rapid experimentation",
      "Built CI/CD pipelines and implemented infrastructure as code to streamline deployment and operations",
    ],
    technologies: [
      "TypeScript",
      "Node.js",
      "Fastify",
      "Prisma",
      "Postgresql",
      "Weaviate",
      "Python",
      "FastAPI",
      "Pulumi",
      "AWS",
      "GitHub Actions",
      "DVC",
      "Swift",
      "Hugging Face",
      "OpenRouter",
      "Google Gemini",
      "OpenAI",
    ],
  },
  {
    company: "Confluent",
    companyUrl: "https://confluent.io/",
    logoPath: "/company-logos/confluent.png",
    title: "Customer Innovation Engineer II",
    location: "Belfast, UK",
    startDate: "2022-04",
    endDate: "2023-05",
    description:
      "Designed and built ML-driven data streaming solutions, wearing multiple hats across engineering, product, and customer-facing roles.",
    responsibilities: [
      "Designed and engineered machine-learning-driven data-streaming solutions",
      "Acted as software engineer, product owner, project manager and technical consultant",
      "Built high-performance stream-processing applications and extensions for ksqlDB and Kafka Connect",
      "Developed real-time PII-redaction capabilities using NLP for low-latency data streams",
      "Leveraged open-source software contributions to establish a strategic partnership with Microsoft",
      "Aided pre-sales and marketing momentum via customer discovery calls, blog posts, and conference booth representation",
    ],
    technologies: [
      "Kafka",
      "Kotlin",
      "Python",
      "Google BigQuery",
      "spaCy",
      "SemaphoreCI",
      "DVC",
    ],
  },
  {
    company: "Sonrai Analytics",
    companyUrl: "https://sonraianalytics.com/",
    logoPath: "/company-logos/sonrai-analytics.png",
    title: "Senior Machine Learning Engineer",
    location: "Belfast, UK",
    startDate: "2020-03",
    endDate: "2022-04",
    description:
      "Technical lead for Data Science at an early-stage health-tech startup, shaping engineering practices and building computer vision pipelines for pathology.",
    responsibilities: [
      "Acted as technical lead for the Data Science team, making foundational architectural decisions and mentoring junior engineers",
      "Developed computer vision models for semantic segmentation, multiple instance learning and object localisation",
      "Engineered full machine learning pipelines, managing algorithms, data sampling, modelling, versioning and iteration",
      "As the 9th employee, drove best practices site-wide, setting direction for MLOps, DevOps, process management and hiring practices",
      "Developed libraries which massively accelerated development, reducing the development time of a new app from weeks to a day",
      "Led research and engineering for a microsatellite instability classification initiative that secured millions in NHS funding",
    ],
    technologies: [
      "Python",
      "PyTorch",
      "FastAPI",
      "Plotly",
      "Leaflet",
      "Docker",
      "AWS",
      "Bitbucket Pipelines",
      "DVC",
      "GeoPandas",
    ],
  },
  {
    company: "Philips",
    companyUrl:
      "https://www.philips.co.uk/healthcare/specialty/health-informatics",
    logoPath: "/company-logos/philips.png",
    title:
      "Graduate Software Engineer → Software Engineer → Senior Software Engineer",
    location: "Belfast, UK",
    startDate: "2017-07",
    endDate: "2020-03",
    description:
      "Led development of production-grade computer vision for computational pathology, from algorithm design through to scalable deployment.",
    responsibilities: [
      "Led development of production-grade computer vision solutions for computational pathology",
      "Drove algorithm conception, data collection and engineering, and deep learning model development",
      "Developed scalable runtime environments and integrated with web applications",
      "Advanced from Graduate Software Engineer (2017) to Senior Software Engineer (2019) through accelerated performance and impact",
    ],
    technologies: [
      "Python",
      "OpenCV",
      "Keras",
      "Docker",
      "Jenkins",
      "RabbitMQ",
      "Ansible",
    ],
  },
  {
    company: "Ulster University",
    companyUrl: "https://www.ulster.ac.uk/",
    logoPath: "/company-logos/ulster-university.png",
    title: "Research Assistant / Software Engineer Summer Intern",
    location: "Belfast, UK",
    startDate: "2016-07",
    endDate: "2016-09",
    description:
      "Built Arduino-based CubeSat prototypes implementing university research on self-managing autonomous systems.",
    responsibilities: [
      "Worked on SPAAACE project developing self-managing systems for CubeSats",
      "Built Arduino-based prototypes implementing autonomic computing principles",
      "Translated academic research into working embedded systems prototypes",
    ],
    technologies: ["Arduino", "C++"],
  },
  {
    company: "Microsoft",
    companyUrl: "https://www.microsoft.com/",
    logoPath: "/company-logos/microsoft.png",
    title: "Software Development Intern",
    location: "London, UK",
    startDate: "2015-07",
    endDate: "2016-06",
    description:
      "Improved Bing auto-suggest across all platforms through code optimization, big data analysis, and interactive dashboards.",
    responsibilities: [
      "Designed, developed and tested C# code improving auto-suggest across all platforms",
      "Optimised large portions of the Bing search stack for performance",
      "Carried out in-depth big data analysis on logs to inform optimization decisions",
      "Developed interactive dashboards for monitoring and analysis",
    ],
    technologies: ["C#", ".NET", "T-SQL"],
  },
  {
    company: "Infosys",
    companyUrl: "https://www.infosys.com/",
    logoPath: "/company-logos/infosys.png",
    title: "Software Development Intern",
    location: "Pune, India",
    startDate: "2014-06",
    endDate: "2014-09",
    description:
      "Built an NLP-powered system that generated graph databases from semantic analysis of web content.",
    responsibilities: [
      "Developed a system integrating NLP analysis with graph database storage",
      "Built semantic relationship mapping for web-page content analysis",
      "Designed and implemented graph database schema for semantic information",
    ],
    technologies: ["Java", "Stanford NLP", "Neo4j"],
  },
];
