import type { Technology } from "@/lib/domain/technology/technology";
export const technologies: Technology[] = [
  {
    slug: "react",
    name: "React",
    description: "A JavaScript library for building user interfaces",
    website: "https://react.dev",
    brandColor: "#61DAFB",
  },
  {
    slug: "next.js",
    name: "Next.js",
    description: "The React Framework for the Web",
    website: "https://nextjs.org",
    brandColor: "#000000",
  },
  {
    slug: "typescript",
    name: "TypeScript",
    description: "TypeScript is JavaScript with syntax for types",
    website: "https://www.typescriptlang.org",
    brandColor: "#3178C6",
  },
  {
    slug: "tailwind css",
    name: "Tailwind CSS",
    description: "A utility-first CSS framework",
    website: "https://tailwindcss.com",
    brandColor: "#06B6D4",
    iconSlug: "tailwindcss",
  },
  {
    slug: "aws",
    name: "AWS",
    description: "Amazon Web Services - Cloud computing platform",
    website: "https://aws.amazon.com",
    brandColor: "#FF9900",
  },
  {
    slug: "java",
    name: "Java",
    website: "https://www.java.com",
    brandColor: "#007396",
  },
  {
    slug: "python",
    name: "Python",
    website: "https://www.python.org",
    brandColor: "#3776AB",
  },
  {
    slug: "pnpm",
    name: "pnpm",
    description: "Fast, disk space efficient package manager",
    website: "https://pnpm.io",
    brandColor: "#F69220",
  },
  {
    slug: "vitest",
    name: "Vitest",
    description: "Next generation testing framework",
    website: "https://vitest.dev",
    brandColor: "#6E9F18",
  },
  {
    slug: "shadcn/ui",
    name: "shadcn/ui",
    description: "Beautifully designed components built with Radix UI and Tailwind CSS",
    website: "https://ui.shadcn.com",
    brandColor: "#000000",
    iconSlug: "shadcnui",
  },
  {
    slug: "github",
    name: "GitHub",
    description: "Development platform for version control and collaboration",
    website: "https://github.com",
    brandColor: "#181717",
  },
  {
    slug: "github actions",
    name: "GitHub Actions",
    description: "Automate your workflow from idea to production",
    website: "https://github.com/features/actions",
    brandColor: "#2088FF",
    iconSlug: "githubactions",
  },
  {
    slug: "terraform",
    name: "Terraform",
    description: "Infrastructure as Code tool",
    website: "https://www.terraform.io",
    brandColor: "#7B42BC",
  },
  {
    slug: "cloudflare pages",
    name: "Cloudflare Pages",
    description: "JAMstack platform for frontend developers",
    website: "https://pages.cloudflare.com",
    brandColor: "#F38020",
    iconSlug: "cloudflarepages",
  },
  {
    slug: "mdx",
    name: "MDX",
    description: "Markdown for the component era",
    website: "https://mdxjs.com",
    brandColor: "#1B1F24",
  },
  {
    slug: "shiki",
    name: "Shiki",
    description: "A beautiful and powerful syntax highlighter",
    website: "https://shiki.style",
    brandColor: "#3C3C3C",
  },
  {
    slug: "fuse.js",
    name: "Fuse.js",
    description: "Lightweight fuzzy-search library",
    website: "https://www.fusejs.io",
  },
  {
    slug: "zod",
    name: "Zod",
    description: "TypeScript-first schema validation",
    website: "https://zod.dev",
    brandColor: "#3E67B1",
  },
  {
    slug: "neo4j",
    name: "Neo4j",
    description: "Graph database management system",
    website: "https://neo4j.com",
    brandColor: "#008CC1",
  },
  {
    slug: "embla carousel",
    name: "Embla Carousel",
    description: "A lightweight carousel library with fluid motion",
    website: "https://www.embla-carousel.com",
  },
  {
    slug: "claude code",
    name: "Claude Code",
    description: "AI-powered coding assistant",
    website: "https://claude.ai",
  },
  {
    slug: "mise",
    name: "Mise",
    description: "Development environment manager",
    website: "https://mise.jdx.dev",
  },
  {
    slug: "c#",
    name: "C#",
    description: "Modern object-oriented programming language",
    website: "https://docs.microsoft.com/en-us/dotnet/csharp/",
    brandColor: "#239120",
    iconSlug: "csharp",
  },
  {
    slug: "weaviate",
    name: "Weaviate",
    description: "Open-source vector database",
    website: "https://weaviate.io",
  },
  {
    slug: "doppler",
    name: "Doppler",
    description: "SecretOps platform for managing environment variables",
    website: "https://www.doppler.com",
    brandColor: "#5729CE",
  },
  {
    slug: "recharts",
    name: "Recharts",
    description: "A composable charting library built on React components",
    website: "https://recharts.org",
    brandColor: "#22B5BF",
  },
  {
    slug: "mermaid",
    name: "Mermaid",
    description: "JavaScript based diagramming and charting tool",
    website: "https://mermaid.js.org",
    brandColor: "#FF3670",
  },
  {
    slug: "lucide react",
    name: "Lucide React",
    description: "Beautiful & consistent icon toolkit",
    website: "https://lucide.dev",
    iconSlug: "lucide",
  },
  {
    slug: "renovate",
    name: "Renovate",
    description: "Automated dependency updates",
    website: "https://docs.renovatebot.com",
    brandColor: "#1A1F6C",
  },
  {
    slug: "coderabbit",
    name: "CodeRabbit",
    description: "AI-powered code review assistant",
    website: "https://coderabbit.ai",
  },
  {
    slug: "dependabot",
    name: "Dependabot",
    description: "Automated dependency updates for GitHub",
    website: "https://github.com/dependabot",
    iconSlug: "dependabot",
  },
  {
    slug: "codeql",
    name: "CodeQL",
    description: "Semantic code analysis engine",
    website: "https://codeql.github.com",
    iconSlug: "github",
  },
  {
    slug: "husky",
    name: "Husky",
    description: "Git hooks made easy",
    website: "https://typicode.github.io/husky",
  },
  {
    slug: "turbopack",
    name: "Turbopack",
    description: "Incremental bundler optimized for JavaScript and TypeScript",
    website: "https://turbo.build/pack",
    iconSlug: "nextdotjs",
  },
  {
    slug: "ccpm",
    name: "CCPM",
    description: "Claude Code Package Manager",
    website: "https://github.com/automazeio/ccpm/",
    iconSlug: "claude",
  },
  {
    slug: "shortcut",
    name: "Shortcut",
    description: "Project management platform for software teams",
    website: "https://shortcut.com",
    brandColor: "#5A67D8",
  },
  {
    slug: "github secrets",
    name: "GitHub Secrets",
    description: "Encrypted environment variables for GitHub Actions",
    website: "https://docs.github.com/en/actions/security-guides/encrypted-secrets",
    iconSlug: "github",
  },
  {
    slug: "cloudflare terraform provider",
    name: "Cloudflare Terraform Provider",
    description: "Terraform provider for Cloudflare",
    website: "https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs",
    iconSlug: "cloudflare",
  },
  {
    slug: "cloudflare dns",
    name: "Cloudflare DNS",
    description: "Fast and secure DNS service",
    website: "https://www.cloudflare.com/dns",
    iconSlug: "cloudflare",
  },
  {
    slug: "cloudflare images",
    name: "Cloudflare Images",
    description: "Image optimization and delivery service",
    website: "https://www.cloudflare.com/products/images",
    iconSlug: "cloudflare",
  },
  {
    slug: "terraform cloud",
    name: "Terraform Cloud",
    description: "Collaborative infrastructure automation platform",
    website: "https://www.hashicorp.com/products/terraform",
    iconSlug: "terraform",
  },
  {
    slug: "tailwind css typography",
    name: "Tailwind CSS Typography",
    description: "Beautiful typographic defaults for HTML you don't control",
    website: "https://github.com/tailwindlabs/tailwindcss-typography",
    iconSlug: "tailwindcss",
  },
  {
    slug: ".net",
    name: ".NET",
    website: "https://dotnet.microsoft.com",
    brandColor: "#512BD4",
  },
  {
    slug: "ansible",
    name: "Ansible",
    description: "IT automation platform",
    website: "https://www.ansible.com",
    brandColor: "#EE0000",
  },
  {
    slug: "apache kafka",
    name: "Apache Kafka",
    description: "Distributed event streaming platform",
    website: "https://kafka.apache.org",
    brandColor: "#231F20",
    iconSlug: "apachekafka",
  },
  {
    slug: "kafka",
    name: "Kafka",
    description: "Distributed event streaming platform",
    website: "https://kafka.apache.org",
    brandColor: "#231F20",
    iconSlug: "apachekafka",
  },
  {
    slug: "arduino",
    name: "Arduino",
    description: "Open-source electronics platform",
    website: "https://www.arduino.cc",
    brandColor: "#00979D",
  },
  {
    slug: "bitbucket pipelines",
    name: "Bitbucket Pipelines",
    description: "CI/CD service built into Bitbucket",
    website: "https://bitbucket.org/product/features/pipelines",
    iconSlug: "bitbucket",
  },
  {
    slug: "c++",
    name: "C++",
    website: "https://isocpp.org",
    brandColor: "#00599C",
    iconSlug: "cplusplus",
  },
  {
    slug: "cloudflare workers",
    name: "Cloudflare Workers",
    description: "Serverless execution environment",
    website: "https://workers.cloudflare.com",
    brandColor: "#F38020",
    iconSlug: "cloudflareworkers",
  },
  {
    slug: "dvc",
    name: "DVC",
    description: "Data Version Control for machine learning projects",
    website: "https://dvc.org",
    brandColor: "#13ADC7",
  },
  {
    slug: "docker",
    name: "Docker",
    description: "Platform for developing, shipping, and running applications",
    website: "https://www.docker.com",
    brandColor: "#2496ED",
  },
  {
    slug: "fastapi",
    name: "FastAPI",
    description: "Modern, fast web framework for building APIs with Python",
    website: "https://fastapi.tiangolo.com",
    brandColor: "#009688",
  },
  {
    slug: "fastify",
    name: "Fastify",
    description: "Fast and low overhead web framework for Node.js",
    website: "https://www.fastify.io",
    brandColor: "#000000",
  },
  {
    slug: "flink",
    name: "Flink",
    description: "Stream processing framework",
    website: "https://flink.apache.org",
    brandColor: "#E6526F",
    iconSlug: "apacheflink",
  },
  {
    slug: "geopandas",
    name: "GeoPandas",
    description: "Python library for working with geospatial data",
    website: "https://geopandas.org",
  },
  {
    slug: "go",
    name: "Go",
    website: "https://go.dev",
    brandColor: "#00ADD8",
  },
  {
    slug: "google bigquery",
    name: "Google BigQuery",
    description: "Serverless, highly scalable data warehouse",
    website: "https://cloud.google.com/bigquery",
    iconSlug: "googlebigquery",
  },
  {
    slug: "google gemini",
    name: "Google Gemini",
    description: "Google's multimodal AI model",
    website: "https://deepmind.google/technologies/gemini/",
    iconSlug: "googlegemini",
  },
  {
    slug: "grafana",
    name: "Grafana",
    description: "Open source analytics and monitoring platform",
    website: "https://grafana.com",
    brandColor: "#F46800",
  },
  {
    slug: "hugging face",
    name: "Hugging Face",
    description: "AI community and model hub",
    website: "https://huggingface.co",
    iconSlug: "huggingface",
  },
  {
    slug: "jenkins",
    name: "Jenkins",
    description: "Open source automation server",
    website: "https://www.jenkins.io",
    brandColor: "#D24939",
  },
  {
    slug: "keras",
    name: "Keras",
    description: "Deep learning API written in Python",
    website: "https://keras.io",
    brandColor: "#D00000",
  },
  {
    slug: "kotlin",
    name: "Kotlin",
    website: "https://kotlinlang.org",
    brandColor: "#7F52FF",
  },
  {
    slug: "leaflet",
    name: "Leaflet",
    description: "Open-source JavaScript library for mobile-friendly maps",
    website: "https://leafletjs.com",
    brandColor: "#199900",
  },
  {
    slug: "node.js",
    name: "Node.js",
    description: "JavaScript runtime built on Chrome's V8 engine",
    website: "https://nodejs.org",
    brandColor: "#339933",
    iconSlug: "nodedotjs",
  },
  {
    slug: "openai",
    name: "OpenAI",
    website: "https://openai.com",
    brandColor: "#412991",
  },
  {
    slug: "opencv",
    name: "OpenCV",
    description: "Open source computer vision library",
    website: "https://opencv.org",
    brandColor: "#5C3EE8",
  },
  {
    slug: "openrouter",
    name: "OpenRouter",
    description: "Unified API for LLM inference",
    website: "https://openrouter.ai",
  },
  {
    slug: "plotly",
    name: "Plotly",
    description: "Interactive graphing library",
    website: "https://plotly.com",
    brandColor: "#3F4F75",
  },
  {
    slug: "postgresql",
    name: "PostgreSQL",
    website: "https://www.postgresql.org",
    brandColor: "#4169E1",
  },
  {
    slug: "prisma",
    name: "Prisma",
    description: "Next-generation ORM for Node.js and TypeScript",
    website: "https://www.prisma.io",
    brandColor: "#2D3748",
  },
  {
    slug: "prometheus",
    name: "Prometheus",
    description: "Systems monitoring and alerting toolkit",
    website: "https://prometheus.io",
    brandColor: "#E6522C",
  },
  {
    slug: "pulumi",
    name: "Pulumi",
    description: "Modern infrastructure as code",
    website: "https://www.pulumi.com",
    brandColor: "#8A3391",
  },
  {
    slug: "pytorch",
    name: "PyTorch",
    description: "Machine learning framework",
    website: "https://pytorch.org",
    brandColor: "#EE4C2C",
  },
  {
    slug: "rabbitmq",
    name: "RabbitMQ",
    description: "Open source message broker",
    website: "https://www.rabbitmq.com",
    brandColor: "#FF6600",
  },
  {
    slug: "sql",
    name: "SQL",
    description: "Domain-specific language for managing relational databases",
    website: "https://en.wikipedia.org/wiki/SQL",
  },
  {
    slug: "semaphoreci",
    name: "SemaphoreCI",
    description: "Continuous integration and delivery platform",
    website: "https://semaphoreci.com",
    iconSlug: "semaphore",
  },
  {
    slug: "stanford nlp",
    name: "Stanford NLP",
    description: "Natural language processing toolkit",
    website: "https://nlp.stanford.edu/software/",
  },
  {
    slug: "swift",
    name: "Swift",
    website: "https://www.swift.org",
    brandColor: "#F05138",
  },
  {
    slug: "t-sql",
    name: "T-SQL",
    description: "Microsoft's extension of SQL",
    website: "https://docs.microsoft.com/en-us/sql/t-sql/",
  },
  {
    slug: "tensorrt",
    name: "TensorRT",
    description: "SDK for high-performance deep learning inference",
    website: "https://developer.nvidia.com/tensorrt",
    brandColor: "#76B900",
    iconSlug: "nvidia",
  },
  {
    slug: "ksqldb",
    name: "ksqlDB",
    description: "Database purpose-built for stream processing",
    website: "https://ksqldb.io",
  },
  {
    slug: "spacy",
    name: "spaCy",
    description: "Industrial-strength natural language processing",
    website: "https://spacy.io",
    brandColor: "#09A3D5",
  },
];
