import type { TechnologyContent } from "@/lib/domain/technology/technology";
export const technologies: TechnologyContent[] = [
  {
    name: "React",
    added: "2025-12-26",
    description: "Component-based UI development for JS/TS",
    website: "https://react.dev",
    type: "library",
  },
  {
    name: "Next.js",
    added: "2026-01-04",
    description: "Full-stack web development built on React",
    website: "https://nextjs.org",
    type: "library",
  },
  {
    name: "TypeScript",
    added: "2025-12-26",
    description: "TypeScript is JavaScript with syntax for types",
    website: "https://www.typescriptlang.org",
    type: "language",
  },
  {
    name: "Tailwind CSS",
    added: "2026-01-04",
    description: "A utility-first CSS framework",
    website: "https://tailwindcss.com",
    type: "library",
  },
  {
    name: "AWS",
    added: "2026-01-04",
    description: "Amazon Web Services - Cloud computing platform",
    website: "https://aws.amazon.com",
    type: "platform",
  },
  {
    name: "Java",
    added: "2026-01-04",
    description:
      "A statically typed, object-oriented language running on the JVM",
    website: "https://www.java.com",
    type: "language",
  },
  {
    name: "Python",
    added: "2026-01-04",
    description:
      "A dynamically typed language widely used for ML, data, and automation",
    website: "https://www.python.org",
    type: "language",
  },
  {
    name: "pnpm",
    added: "2026-01-04",
    description: "Fast, disk space efficient package manager",
    website: "https://pnpm.io",
    type: "tool",
  },
  {
    name: "Vitest",
    added: "2026-01-04",
    description: "Modern unit testing for JS/TS with a familiar Jest-style API",
    website: "https://vitest.dev",
    type: "library",
  },
  {
    name: "shadcn/ui",
    added: "2026-01-04",
    description:
      "Beautifully designed components built with Radix UI and Tailwind CSS",
    website: "https://ui.shadcn.com",
    type: "library",
  },
  {
    name: "GitHub",
    added: "2026-01-04",
    description: "Development platform for version control and collaboration",
    website: "https://github.com",
    type: "platform",
  },
  {
    name: "GitHub Actions",
    added: "2026-01-04",
    description:
      "A workflow automation platform integrated with GitHub repositories",
    website: "https://github.com/features/actions",
    type: "tool",
  },
  {
    name: "Terraform",
    added: "2026-01-04",
    description:
      "Infrastructure as code for building, changing, and versioning cloud resources",
    website: "https://www.terraform.io",
    type: "language",
  },
  {
    name: "Cloudflare Pages",
    added: "2026-01-04",
    description: "JAMstack platform for frontend developers",
    website: "https://pages.cloudflare.com",
    type: "platform",
  },
  {
    name: "MDX",
    added: "2026-01-04",
    description: "Markdown for the component era",
    website: "https://mdxjs.com",
    type: "library",
  },
  {
    name: "Shiki",
    added: "2026-01-04",
    description: "A beautiful and powerful code syntax highlighter",
    website: "https://shiki.style",
    type: "library",
  },
  {
    name: "Fuse.js",
    added: "2026-01-04",
    description: "Lightweight, client-side, fuzzy-search library",
    website: "https://www.fusejs.io",
    type: "library",
  },
  {
    name: "Zod",
    added: "2026-01-04",
    description: "TypeScript-first schema validation",
    website: "https://zod.dev",
    type: "library",
  },
  {
    name: "Neo4j",
    added: "2026-01-04",
    description: "Graph database management system",
    website: "https://neo4j.com",
    type: "database",
  },
  {
    name: "Embla Carousel",
    added: "2026-01-04",
    description: "A lightweight carousel library with fluid motion",
    website: "https://www.embla-carousel.com",
    type: "library",
  },
  {
    name: "Claude Code",
    added: "2026-01-04",
    description: "AI-powered coding assistant",
    website: "https://claude.ai",
    type: "tool",
  },
  {
    name: "Codex",
    added: "2026-06-21",
    description: "OpenAI agentic coding assistant",
    website: "https://developers.openai.com/codex",
    type: "tool",
  },
  {
    name: "Mise",
    added: "2026-01-04",
    description:
      "Tool version management, env var automation, and task execution for projects",
    website: "https://mise.jdx.dev",
    type: "tool",
  },
  {
    name: "C#",
    added: "2026-01-04",
    description: "A statically typed, object-oriented language running on .NET",
    website: "https://docs.microsoft.com/en-us/dotnet/csharp/",
    type: "language",
  },
  {
    name: "Weaviate",
    added: "2026-01-04",
    description: "Open-source vector database",
    website: "https://weaviate.io",
    type: "database",
  },
  {
    name: "Doppler",
    added: "2026-01-04",
    description: "SecretOps platform for managing environment variables",
    website: "https://www.doppler.com",
    type: "tool",
  },
  {
    name: "Recharts",
    added: "2026-01-04",
    description: "A composable charting library built on React components",
    website: "https://recharts.org",
    type: "library",
  },
  {
    name: "Mermaid",
    added: "2026-01-04",
    description: "JavaScript based diagramming and charting tool",
    website: "https://mermaid.js.org",
    type: "library",
  },
  {
    name: "Lucide React",
    added: "2026-01-04",
    description: "Beautiful & consistent icon toolkit",
    website: "https://lucide.dev",
    iconSlug: "lucide",
    type: "library",
  },
  {
    name: "Renovate",
    added: "2026-01-04",
    description: "Automated dependency updates",
    website: "https://docs.renovatebot.com",
    type: "tool",
  },
  {
    name: "CodeRabbit",
    added: "2026-01-04",
    description: "AI-powered code review assistant",
    website: "https://coderabbit.ai",
    type: "tool",
  },
  {
    name: "Greptile",
    added: "2026-06-20",
    description: "AI code reviewer with whole-codebase context",
    website: "https://www.greptile.com",
    type: "tool",
  },
  {
    name: "Qodo",
    added: "2026-06-21",
    description: "AI-powered multi-agent code review platform",
    website: "https://www.qodo.ai",
    type: "tool",
  },
  {
    name: "CLA Assistant",
    added: "2026-01-11",
    description: "Contributor License Agreement automation for GitHub",
    website: "https://cla-assistant.io",
    type: "tool",
  },
  {
    name: "Dependabot",
    added: "2026-01-04",
    description: "Automated dependency updates for GitHub",
    website: "https://github.com/dependabot",
    type: "tool",
  },
  {
    name: "CodeQL",
    added: "2026-01-04",
    description: "Semantic code analysis engine",
    website: "https://codeql.github.com",
    type: "tool",
  },
  {
    name: "Husky",
    added: "2026-01-04",
    description: "Git hooks made easy",
    website: "https://typicode.github.io/husky",
    type: "tool",
  },
  {
    name: "Turbopack",
    added: "2026-01-04",
    description: "Incremental bundler optimized for JavaScript and TypeScript",
    website: "https://turbo.build/pack",
    type: "tool",
  },
  {
    name: "CCPM",
    added: "2026-01-04",
    description: "Claude Code Project Management",
    website: "https://github.com/automazeio/ccpm/",
    type: "tool",
  },
  {
    name: "Shortcut",
    added: "2026-01-04",
    description: "Project management platform",
    website: "https://shortcut.com",
    type: "tool",
  },
  {
    name: "GitHub Secrets",
    added: "2026-01-04",
    description: "Encrypted environment variables for GitHub Actions",
    website:
      "https://docs.github.com/en/actions/security-guides/encrypted-secrets",
    iconSlug: "github",
    type: "tool",
  },
  {
    name: "Cloudflare Terraform Provider",
    added: "2026-01-04",
    website:
      "https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs",
    iconSlug: "cloudflare",
    type: "library",
  },
  {
    name: "Cloudflare DNS",
    added: "2026-01-04",
    website: "https://www.cloudflare.com/dns",
    iconSlug: "cloudflare",
    type: "platform",
  },
  {
    name: "Cloudflare Rulesets",
    added: "2026-01-11",
    description: "Rules for transforming and routing HTTP requests at the edge",
    website: "https://developers.cloudflare.com/ruleset-engine/",
    iconSlug: "cloudflare",
    type: "platform",
  },
  {
    name: "Cloudflare Images",
    added: "2026-01-04",
    description: "Image optimization and delivery service",
    website: "https://www.cloudflare.com/products/images",
    iconSlug: "cloudflare",
    type: "platform",
  },
  {
    name: "Cloudflare R2",
    added: "2026-02-14",
    description: "S3-compatible object storage with zero egress fees",
    website: "https://www.cloudflare.com/products/r2",
    iconSlug: "cloudflare",
    type: "platform",
  },
  {
    name: "Terraform Cloud",
    added: "2026-01-04",
    description:
      "A SaaS platform for running Terraform and managing infrastructure state",
    website: "https://www.hashicorp.com/products/terraform",
    iconSlug: "terraform",
    type: "platform",
  },
  {
    name: "Tailwind CSS Typography",
    added: "2026-01-04",
    description: "Beautiful typographic defaults for HTML you don't control",
    website: "https://github.com/tailwindlabs/tailwindcss-typography",
    iconSlug: "tailwindcss",
    type: "library",
  },
  {
    name: ".NET",
    added: "2026-01-04",
    website: "https://dotnet.microsoft.com",
    type: "platform",
  },
  {
    name: "Ansible",
    added: "2026-01-04",
    description:
      "A tool for automating configuration, deployment, and orchestration",
    website: "https://www.ansible.com",
    type: "tool",
  },
  {
    name: "Kafka",
    added: "2026-01-04",
    description: "Distributed event streaming platform",
    website: "https://kafka.apache.org",
    iconSlug: "apachekafka",
    type: "platform",
  },
  {
    name: "Arduino",
    added: "2026-01-04",
    description:
      "Microcontroller boards and tools for building interactive electronic projects",
    website: "https://www.arduino.cc",
    type: "platform",
  },
  {
    name: "Bitbucket Pipelines",
    added: "2026-01-04",
    description: "CI/CD service built into Bitbucket",
    website: "https://bitbucket.org/product/features/pipelines",
    type: "tool",
  },
  {
    name: "C++",
    added: "2026-01-04",
    website: "https://isocpp.org",
    type: "language",
  },
  {
    name: "Cloudflare Workers",
    added: "2026-01-04",
    description: "Serverless execution environment",
    website: "https://workers.cloudflare.com",
    type: "platform",
  },
  {
    name: "DVC",
    added: "2026-01-04",
    description: "Data Version Control for machine learning projects",
    website: "https://dvc.org",
    type: "tool",
  },
  {
    name: "Docker",
    added: "2026-01-04",
    description:
      "A platform for packaging, distributing, and running applications in containers",
    website: "https://www.docker.com",
    type: "tool",
  },
  {
    name: "FastAPI",
    added: "2026-01-04",
    description: "Modern, fast web framework for building APIs with Python",
    website: "https://fastapi.tiangolo.com",
    type: "library",
  },
  {
    name: "Fastify",
    added: "2026-01-04",
    description: "Fast and low overhead web framework for Node.js",
    website: "https://www.fastify.io",
    type: "library",
  },
  {
    name: "Flink",
    added: "2026-01-04",
    description:
      "A distributed system for stateful, high-throughput, low-latency data processing",
    website: "https://flink.apache.org",
    iconSlug: "apacheflink",
    type: "platform",
  },
  {
    name: "GeoPandas",
    added: "2026-01-04",
    description: "Python library for working with geospatial data",
    website: "https://geopandas.org",
    type: "library",
  },
  {
    name: "Go",
    added: "2026-01-04",
    description:
      "A statically typed, compiled language designed for simplicity and concurrency",
    website: "https://go.dev",
    type: "language",
  },
  {
    name: "Google BigQuery",
    added: "2026-01-04",
    description: "Serverless, highly scalable data warehouse",
    website: "https://cloud.google.com/bigquery",
    type: "database",
  },
  {
    name: "Google Gemini",
    added: "2026-01-04",
    description: "A cloud-based multimodal large language model",
    website: "https://deepmind.google/technologies/gemini/",
    type: "tool",
  },
  {
    name: "Grafana",
    added: "2026-01-04",
    description: "Open source analytics and monitoring platform",
    website: "https://grafana.com",
    type: "tool",
  },
  {
    name: "Hugging Face",
    added: "2026-01-04",
    description: "AI community and model hub",
    website: "https://huggingface.co",
    type: "library",
  },
  {
    name: "Jenkins",
    added: "2026-01-04",
    description:
      "A CI/CD platform for automating software development workflows",
    website: "https://www.jenkins.io",
    type: "tool",
  },
  {
    name: "Keras",
    added: "2026-01-04",
    description: "A Python library for designing and training neural networks",
    website: "https://keras.io",
    type: "library",
  },
  {
    name: "Kotlin",
    added: "2026-01-04",
    description:
      "A modern JVM language blending OOP and functional programming",
    website: "https://kotlinlang.org",
    type: "language",
  },
  {
    name: "Leaflet",
    added: "2026-01-04",
    description: "A JavaScript library for interactive maps on the web",
    website: "https://leafletjs.com",
    type: "library",
  },
  {
    name: "Node.js",
    added: "2026-01-04",
    description: "JavaScript runtime built on Chrome's V8 engine",
    website: "https://nodejs.org",
    type: "platform",
  },
  {
    name: "OpenAI",
    added: "2026-01-04",
    website: "https://openai.com",
    type: "tool",
  },
  {
    name: "OpenCV",
    added: "2026-01-04",
    description: "Open source computer vision library",
    website: "https://opencv.org",
    type: "library",
  },
  {
    name: "OpenRouter",
    added: "2026-01-04",
    description: "Unified API for LLM inference",
    website: "https://openrouter.ai",
    type: "tool",
  },
  {
    name: "Plotly",
    added: "2026-01-04",
    description:
      "A Python (and JS) library for building interactive charts and dashboards",
    website: "https://plotly.com",
    type: "library",
  },
  {
    name: "PostgreSQL",
    added: "2026-01-04",
    description:
      "A relational database optimized for extensibility and advanced data management",
    website: "https://www.postgresql.org",
    type: "database",
  },
  {
    name: "Prisma",
    added: "2026-01-04",
    description: "A TypeScript and Node.js ORM",
    website: "https://www.prisma.io",
    type: "library",
  },
  {
    name: "Prometheus",
    added: "2026-01-04",
    description: "A time-series database for collecting and querying metrics",
    website: "https://prometheus.io",
    type: "database",
  },
  {
    name: "Pulumi",
    added: "2026-01-04",
    description: "Infrastructure as code using general-purpose languages",
    website: "https://www.pulumi.com",
    type: "library",
  },
  {
    name: "PyTorch",
    added: "2026-01-04",
    description:
      "A Python library for designing, training, and running neural networks",
    website: "https://pytorch.org",
    type: "library",
  },
  {
    name: "RabbitMQ",
    added: "2026-01-04",
    description: "A broker for asynchronous messaging and task distribution",
    website: "https://www.rabbitmq.com",
    type: "platform",
  },
  {
    name: "SQL",
    added: "2026-01-04",
    description: "Domain-specific language for managing relational databases",
    website: "https://en.wikipedia.org/wiki/SQL",
    type: "language",
  },
  {
    name: "SemaphoreCI",
    added: "2026-01-04",
    description:
      "A cloud-based CI/CD platform for automating software development workflows",
    website: "https://semaphoreci.com",
    iconSlug: "semaphore",
    type: "tool",
  },
  {
    name: "Stanford NLP",
    added: "2026-01-04",
    description: "Natural language processing toolkit",
    website: "https://nlp.stanford.edu/software/",
    type: "library",
  },
  {
    name: "Swift",
    added: "2026-01-04",
    description:
      "A compiled, type-safe language for developing applications across Apple platforms",
    website: "https://www.swift.org",
    type: "language",
  },
  {
    name: "T-SQL",
    added: "2026-01-04",
    description: "Microsoft's extension of SQL",
    website: "https://docs.microsoft.com/en-us/sql/t-sql/",
    type: "language",
  },
  {
    name: "TensorRT",
    added: "2026-01-04",
    description: "SDK for high-performance deep learning inference",
    website: "https://developer.nvidia.com/tensorrt",
    type: "library",
  },
  {
    name: "ksqlDB",
    added: "2026-01-04",
    description: "Database purpose-built for stream processing",
    website: "https://ksqldb.io",
    type: "tool",
  },
  {
    name: "spaCy",
    added: "2026-01-04",
    description: "Industrial-strength natural language processing",
    website: "https://spacy.io",
    type: "library",
  },
  {
    name: "Shapely",
    added: "2026-01-04",
    description: "An SDK for embedded geospatial operations",
    website: "https://shapely.readthedocs.io/en/latest/",
    type: "library",
  },
  {
    name: "OpenSlide",
    added: "2026-01-04",
    description: "An SDK for reading pathology image formats",
    website: "https://github.com/openslide/openslide-python",
    type: "library",
  },
  {
    name: "R",
    added: "2026-01-04",
    website: "https://www.r-project.org/",
    type: "language",
  },
  {
    name: "Shiny",
    added: "2026-01-04",
    website: "https://shiny.posit.co/",
    type: "library",
  },
  {
    name: "AWS Textract",
    added: "2026-01-04",
    description:
      "Machine learning service that automatically extracts text, handwriting, and data from scanned documents",
    website: "https://aws.amazon.com/textract/",
    type: "tool",
  },
  {
    name: "PyPika",
    added: "2026-01-04",
    description: "A Python SQL query builder",
    website: "https://github.com/kayak/pypika",
    type: "library",
  },
  {
    name: "Sigma.js",
    added: "2026-02-12",
    description: "WebGL-powered graph visualization for the web",
    website: "https://www.sigmajs.org",
    type: "library",
  },
  {
    name: "PostHog",
    added: "2026-02-14",
    description:
      "Open source product analytics, session replay, and experimentation",
    website: "https://posthog.com",
    type: "platform",
  },
  {
    name: "cooklang-rs",
    added: "2026-02-28",
    description:
      "Rust parser and scaling engine for the Cooklang recipe format, with WASM/TypeScript bindings for in-browser use",
    website: "https://github.com/cooklang/cooklang-rs",
    type: "library",
  },
  {
    name: "Better Auth",
    added: "2026-05-27",
    description:
      "TypeScript-first, self-hosted authentication library with config-as-code",
    website: "https://better-auth.com",
    type: "library",
  },
  {
    name: "Drizzle",
    added: "2026-05-28",
    description:
      "TypeScript ORM with type-safe queries and dialect-specific schema definitions",
    website: "https://orm.drizzle.team",
    type: "library",
  },
  {
    name: "Hono",
    added: "2026-05-28",
    description:
      "Lightweight HTTP framework for Cloudflare Workers, Node.js, Deno, and Bun",
    website: "https://hono.dev",
    type: "library",
  },
  {
    name: "Hyperdrive",
    added: "2026-05-28",
    description:
      "Cloudflare connection pooling service for Workers connecting to external databases",
    website: "https://developers.cloudflare.com/hyperdrive/",
    iconSlug: "cloudflare",
    type: "platform",
  },
  {
    name: "Neon",
    added: "2026-05-28",
    description:
      "Serverless Postgres with scale-to-zero, branching, and a generous free tier",
    website: "https://neon.com",
    type: "database",
  },
  {
    name: "Google OAuth",
    added: "2026-06-19",
    description:
      "Sign in with Google via OAuth 2.0 / OpenID Connect, configured through a Google Cloud project",
    website: "https://developers.google.com/identity",
    iconSlug: "google",
    type: "platform",
  },
  {
    name: "GitHub OAuth",
    added: "2026-06-19",
    description:
      "Sign in with GitHub via OAuth 2.0, configured through a GitHub OAuth App",
    website: "https://docs.github.com/en/apps/oauth-apps",
    iconSlug: "github",
    type: "platform",
  },
  {
    name: "Trivy",
    added: "2026-06-21",
    description:
      "Open source security scanner for IaC, container images, and dependency vulnerabilities",
    website: "https://trivy.dev",
    type: "tool",
  },
  {
    name: "SonarQube",
    added: "2026-06-26",
    description:
      "Continuous code quality and security platform: maintainability metrics, duplication, cognitive complexity, coverage gating, and SAST behind a pass/fail quality gate",
    website: "https://www.sonarsource.com/products/sonarqube/",
    iconSlug: "sonarqubeserver",
    type: "tool",
  },
];
