import type { Technology } from "@/lib/domain/technology/technology";

export const technologies: Technology[] = [
  {
    slug: "react",
    name: "React",
    description: "A JavaScript library for building user interfaces",
    website: "https://react.dev",
    brandColor: "#61DAFB",
    hasCustomIcon: false,
  },
  {
    slug: "next.js",
    name: "Next.js",
    description: "The React Framework for the Web",
    website: "https://nextjs.org",
    brandColor: "#000000",
    hasCustomIcon: false,
  },
  {
    slug: "typescript",
    name: "TypeScript",
    description: "TypeScript is JavaScript with syntax for types",
    website: "https://www.typescriptlang.org",
    brandColor: "#3178C6",
    hasCustomIcon: false,
  },
  {
    slug: "tailwind css",
    name: "Tailwind CSS",
    description: "A utility-first CSS framework",
    website: "https://tailwindcss.com",
    brandColor: "#06B6D4",
    iconSlug: "tailwindcss",
    hasCustomIcon: false,
  },
  {
    slug: "aws",
    name: "AWS",
    description: "Amazon Web Services - Cloud computing platform",
    website: "https://aws.amazon.com",
    brandColor: "#FF9900",
    hasCustomIcon: true,
    customIconName: "aws",
  },
  {
    slug: "java",
    name: "Java",
    description: "Object-oriented programming language",
    website: "https://www.java.com",
    brandColor: "#007396",
    hasCustomIcon: true,
    customIconName: "java",
  },
  {
    slug: "python",
    name: "Python",
    description: "High-level programming language",
    website: "https://www.python.org",
    brandColor: "#3776AB",
    hasCustomIcon: false,
  },
  {
    slug: "pnpm",
    name: "pnpm",
    description: "Fast, disk space efficient package manager",
    website: "https://pnpm.io",
    brandColor: "#F69220",
    hasCustomIcon: false,
  },
  {
    slug: "vitest",
    name: "Vitest",
    description: "Next generation testing framework",
    website: "https://vitest.dev",
    brandColor: "#6E9F18",
    hasCustomIcon: false,
  },
  {
    slug: "shadcn/ui",
    name: "shadcn/ui",
    description: "Beautifully designed components built with Radix UI and Tailwind CSS",
    website: "https://ui.shadcn.com",
    brandColor: "#000000",
    iconSlug: "shadcnui",
    hasCustomIcon: false,
  },
  {
    slug: "github",
    name: "GitHub",
    description: "Development platform for version control and collaboration",
    website: "https://github.com",
    brandColor: "#181717",
    hasCustomIcon: false,
  },
  {
    slug: "github actions",
    name: "GitHub Actions",
    description: "Automate your workflow from idea to production",
    website: "https://github.com/features/actions",
    brandColor: "#2088FF",
    iconSlug: "githubactions",
    hasCustomIcon: false,
  },
  {
    slug: "terraform",
    name: "Terraform",
    description: "Infrastructure as Code tool",
    website: "https://www.terraform.io",
    brandColor: "#7B42BC",
    hasCustomIcon: false,
  },
  {
    slug: "cloudflare pages",
    name: "Cloudflare Pages",
    description: "JAMstack platform for frontend developers",
    website: "https://pages.cloudflare.com",
    brandColor: "#F38020",
    iconSlug: "cloudflarepages",
    hasCustomIcon: false,
  },
  {
    slug: "mdx",
    name: "MDX",
    description: "Markdown for the component era",
    website: "https://mdxjs.com",
    brandColor: "#1B1F24",
    hasCustomIcon: false,
  },
  {
    slug: "shiki",
    name: "Shiki",
    description: "A beautiful and powerful syntax highlighter",
    website: "https://shiki.style",
    brandColor: "#3C3C3C",
    hasCustomIcon: true,
    customIconName: "shiki",
  },
  {
    slug: "fuse.js",
    name: "Fuse.js",
    description: "Lightweight fuzzy-search library",
    website: "https://www.fusejs.io",
    hasCustomIcon: true,
    customIconName: "fusejs",
  },
  {
    slug: "zod",
    name: "Zod",
    description: "TypeScript-first schema validation",
    website: "https://zod.dev",
    brandColor: "#3E67B1",
    hasCustomIcon: false,
  },
  {
    slug: "neo4j",
    name: "Neo4j",
    description: "Graph database management system",
    website: "https://neo4j.com",
    brandColor: "#008CC1",
    hasCustomIcon: true,
    customIconName: "neo4j",
  },
  {
    slug: "embla carousel",
    name: "Embla Carousel",
    description: "A lightweight carousel library with fluid motion",
    website: "https://www.embla-carousel.com",
    hasCustomIcon: true,
    customIconName: "embla-carousel",
  },
  {
    slug: "claude code",
    name: "Claude Code",
    description: "AI-powered coding assistant",
    website: "https://claude.ai",
    hasCustomIcon: true,
    customIconName: "claudecode",
  },
  {
    slug: "mise",
    name: "Mise",
    description: "Development environment manager",
    website: "https://mise.jdx.dev",
    hasCustomIcon: true,
    customIconName: "mise",
  },
  {
    slug: "c#",
    name: "C#",
    description: "Modern object-oriented programming language",
    website: "https://docs.microsoft.com/en-us/dotnet/csharp/",
    brandColor: "#239120",
    iconSlug: "csharp",
    hasCustomIcon: true,
    customIconName: "csharp",
  },
  {
    slug: "weaviate",
    name: "Weaviate",
    description: "Open-source vector database",
    website: "https://weaviate.io",
    hasCustomIcon: true,
    customIconName: "weaviate",
  },
  {
    slug: "doppler",
    name: "Doppler",
    description: "SecretOps platform for managing environment variables",
    website: "https://www.doppler.com",
    brandColor: "#5729CE",
    hasCustomIcon: true,
    customIconName: "doppler",
  },
  {
    slug: "recharts",
    name: "Recharts",
    description: "A composable charting library built on React components",
    website: "https://recharts.org",
    brandColor: "#22B5BF",
    hasCustomIcon: false,
  },
  {
    slug: "mermaid",
    name: "Mermaid",
    description: "JavaScript based diagramming and charting tool",
    website: "https://mermaid.js.org",
    brandColor: "#FF3670",
    hasCustomIcon: false,
  },
  {
    slug: "lucide react",
    name: "Lucide React",
    description: "Beautiful & consistent icon toolkit",
    website: "https://lucide.dev",
    iconSlug: "lucide",
    hasCustomIcon: false,
  },
  {
    slug: "renovate",
    name: "Renovate",
    description: "Automated dependency updates",
    website: "https://docs.renovatebot.com",
    brandColor: "#1A1F6C",
    hasCustomIcon: false,
  },
  {
    slug: "coderabbit",
    name: "CodeRabbit",
    description: "AI-powered code review assistant",
    website: "https://coderabbit.ai",
    hasCustomIcon: false,
  },
  {
    slug: "dependabot",
    name: "Dependabot",
    description: "Automated dependency updates for GitHub",
    website: "https://github.com/dependabot",
    iconSlug: "dependabot",
    hasCustomIcon: false,
  },
  {
    slug: "codeql",
    name: "CodeQL",
    description: "Semantic code analysis engine",
    website: "https://codeql.github.com",
    iconSlug: "github",
    hasCustomIcon: false,
  },
  {
    slug: "husky",
    name: "Husky",
    description: "Git hooks made easy",
    website: "https://typicode.github.io/husky",
    hasCustomIcon: false,
  },
  {
    slug: "turbopack",
    name: "Turbopack",
    description: "Incremental bundler optimized for JavaScript and TypeScript",
    website: "https://turbo.build/pack",
    iconSlug: "nextdotjs",
    hasCustomIcon: false,
  },
  {
    slug: "ccpm",
    name: "CCPM",
    description: "Claude Code Package Manager",
    website: "https://github.com/automazeio/ccpm/",
    iconSlug: "claude",
    hasCustomIcon: false,
  },
  {
    slug: "shortcut",
    name: "Shortcut",
    description: "Project management platform for software teams",
    website: "https://shortcut.com",
    brandColor: "#5A67D8",
    hasCustomIcon: false,
  },
  {
    slug: "github secrets",
    name: "GitHub Secrets",
    description: "Encrypted environment variables for GitHub Actions",
    website: "https://docs.github.com/en/actions/security-guides/encrypted-secrets",
    iconSlug: "github",
    hasCustomIcon: false,
  },
  {
    slug: "cloudflare terraform provider",
    name: "Cloudflare Terraform Provider",
    description: "Terraform provider for Cloudflare",
    website: "https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs",
    iconSlug: "cloudflare",
    hasCustomIcon: false,
  },
  {
    slug: "cloudflare dns",
    name: "Cloudflare DNS",
    description: "Fast and secure DNS service",
    website: "https://www.cloudflare.com/dns",
    iconSlug: "cloudflare",
    hasCustomIcon: false,
  },
  {
    slug: "cloudflare images",
    name: "Cloudflare Images",
    description: "Image optimization and delivery service",
    website: "https://www.cloudflare.com/products/images",
    iconSlug: "cloudflare",
    hasCustomIcon: false,
  },
  {
    slug: "terraform cloud",
    name: "Terraform Cloud",
    description: "Collaborative infrastructure automation platform",
    website: "https://www.hashicorp.com/products/terraform",
    iconSlug: "terraform",
    hasCustomIcon: false,
  },
  {
    slug: "tailwind css typography",
    name: "Tailwind CSS Typography",
    description: "Beautiful typographic defaults for HTML you don't control",
    website: "https://github.com/tailwindlabs/tailwindcss-typography",
    iconSlug: "tailwindcss",
    hasCustomIcon: false,
  },
];
