apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: t3-code
resources:
  - ../../base/t3-code
  - persistent-volume.yaml
  - doppler-secret.yaml
patches:
  - path: deployment-patch.yaml
  - path: service-patch.yaml
labels:
  - pairs:
      homelab.dev/environment: remote-development
    includeSelectors: false
    includeTemplates: true
