export const ingredients = [
  // Proteins
  { name: "chicken breast", category: "protein" },
  { name: "turkey mince", category: "protein" },
  { name: "chorizo", category: "protein" },
  { name: "bacon", category: "protein" },
  { name: "pork sausage", category: "protein" },
  { name: "eggs", category: "protein" },

  // Vegetables
  { name: "white onion", category: "vegetable" },
  { name: "red onion", category: "vegetable" },
  { name: "onion", category: "vegetable" },
  { name: "bell pepper", category: "vegetable" },
  { name: "red pepper", category: "vegetable" },
  { name: "garlic", category: "vegetable" },
  { name: "peas", category: "vegetable" },
  { name: "chopped tomatoes", category: "vegetable" },
  { name: "tomato passata", category: "vegetable" },
  { name: "frozen vegetables", category: "vegetable" },
  { name: "fresh tomatoes", category: "vegetable" },
  { name: "garlic puree", category: "vegetable" },
  { name: "tomato puree", category: "vegetable" },
  { name: "frozen peas", category: "vegetable" },
  { name: "frozen peppers", category: "vegetable" },
  { name: "spinach", category: "vegetable" },
  { name: "vine tomato", category: "vegetable" },
  { name: "spring onion", category: "vegetable" },
  { name: "leek", category: "vegetable" },
  { name: "potato", category: "vegetable" },
  { name: "cherry tomato", category: "vegetable" },
  { name: "carrot", category: "vegetable" },
  { name: "sweet potato", category: "vegetable" },
  { name: "lettuce", category: "vegetable" },

  // Legumes
  { name: "mixed beans", category: "legume" },
  { name: "chickpeas", category: "legume" },
  { name: "red lentils", category: "legume" },

  // Fruit
  { name: "avocado", category: "fruit" },
  { name: "lime", category: "fruit" },

  // Dairy
  { name: "butter", category: "dairy" },
  { name: "unsalted butter", category: "dairy" },
  { name: "double cream", category: "dairy" },
  { name: "single cream", category: "dairy" },
  { name: "creme fraiche", category: "dairy" },
  { name: "mascarpone", category: "dairy" },
  { name: "milk", category: "dairy" },
  { name: "cheddar cheese", category: "dairy" },
  { name: "parmesan", category: "dairy" },
  { name: "grana padano", category: "dairy" },
  { name: "cream cheese", category: "dairy" },
  { name: "light soft cheese", category: "dairy" },
  { name: "mozzarella", category: "dairy" },

  // Grains & Pasta
  { name: "rice", category: "grain" },
  { name: "arborio rice", category: "grain" },
  { name: "macaroni", category: "grain" },
  { name: "penne pasta", category: "grain" },
  { name: "large pasta shells", category: "grain" },
  { name: "pasta", category: "grain" },
  { name: "long grain rice", category: "grain" },
  { name: "paella rice", category: "grain" },
  { name: "tortilla wrap", category: "grain" },
  { name: "farfalle", category: "grain" },
  { name: "plain flour", category: "grain" },
  { name: "bread flour", category: "grain" },
  { name: "cornflour", category: "grain" },
  { name: "semolina", category: "grain" },
  { name: "bread", category: "grain" },
  { name: "noodles", category: "grain" },
  { name: "bap", category: "grain" },
  { name: "rolled oats", category: "grain" },

  // Herbs
  { name: "fresh basil", category: "herb" },
  { name: "fresh rosemary", category: "herb" },
  { name: "fresh parsley", category: "herb" },
  { name: "fresh coriander", category: "herb" },
  { name: "oregano", category: "herb" },
  { name: "thyme", category: "herb" },
  { name: "italian herbs", category: "herb" },

  // Spices & Seasonings
  { name: "curry powder", category: "spice" },
  { name: "hot chilli powder", category: "spice" },
  { name: "ground coriander", category: "spice" },
  { name: "cayenne pepper", category: "spice" },
  { name: "paprika", category: "spice" },
  { name: "smoked paprika", category: "spice" },
  { name: "chilli", category: "spice" },
  { name: "chilli flakes", category: "spice" },
  { name: "tikka curry powder", category: "spice" },
  { name: "italian seasoning", category: "spice" },
  { name: "red chilli powder", category: "spice" },
  { name: "salt", category: "spice" },
  { name: "sea salt", category: "spice" },
  { name: "black pepper", category: "spice" },
  { name: "peri peri salt", category: "spice" },
  { name: "cajun seasoning", category: "spice" },
  { name: "taco seasoning", category: "spice" },
  { name: "MSG", category: "spice" },
  { name: "five spice", category: "spice" },
  { name: "white pepper", category: "spice" },
  { name: "dried parsley", category: "herb" },
  { name: "turmeric", category: "spice" },
  { name: "saffron", category: "spice" },
  { name: "cumin", category: "spice" },
  { name: "garlic granules", category: "spice" },
  { name: "garlic powder", category: "spice" },
  { name: "onion salt", category: "spice" },
  { name: "fajita and taco mix", category: "spice" },
  { name: "chilli powder", category: "spice" },
  { name: "ginger", category: "spice" },
  { name: "avocado topping", category: "spice" },

  // Condiments & Sauces
  { name: "basil pesto", category: "condiment" },
  { name: "soy sauce", category: "condiment" },
  { name: "lime juice", category: "condiment" },
  { name: "peanut butter", category: "condiment" },
  { name: "honey", category: "condiment" },
  { name: "sweet chilli sauce", category: "condiment" },
  { name: "chipotle paste", category: "condiment" },
  { name: "mayonnaise", category: "condiment" },
  { name: "guacamole mix", category: "condiment" },
  { name: "sun-dried tomato pesto", category: "condiment" },
  { name: "hoisin sauce", category: "condiment" },
  { name: "dark soy sauce", category: "condiment" },
  { name: "light soy sauce", category: "condiment" },
  { name: "rice wine vinegar", category: "condiment" },
  { name: "peri peri sauce", category: "condiment" },
  { name: "harissa paste", category: "condiment" },
  { name: "ballymaloe relish", category: "condiment" },

  // Sweets
  { name: "sugar", category: "sweets" },
  { name: "brown sugar", category: "sweets" },
  { name: "icing sugar", category: "sweets" },
  { name: "milk chocolate", category: "sweets" },
  { name: "dark chocolate", category: "sweets" },
  { name: "caramel", category: "sweets" },
  { name: "dulce de leche", category: "sweets" },

  // Oils & Fats
  { name: "vegetable oil", category: "oil-fat" },
  { name: "olive oil", category: "oil-fat" },
  { name: "extra virgin olive oil", category: "oil-fat" },
  { name: "coconut milk", category: "oil-fat" },
  { name: "margarine", category: "oil-fat" },

  // Liquids
  { name: "chicken stock", category: "liquid" },
  { name: "vegetable stock", category: "liquid" },
  { name: "pasta water", category: "liquid" },
  { name: "white wine", category: "liquid" },
  { name: "water", category: "liquid" },
  { name: "orange juice", category: "liquid" },

  // Other
  { name: "dry yeast", category: "other" },
  { name: "prawn crackers", category: "other" },
  { name: "garlic bread", category: "other" },
  { name: "chips", category: "other" },
  { name: "potato wedges", category: "other" },
  { name: "self-raising flour", category: "other" },
  { name: "caster sugar", category: "sweets" },
  { name: "flour", category: "other" },
  { name: "cornflakes", category: "other" },
  { name: "cashew nuts", category: "other" },
  { name: "cashews", category: "other" },
  { name: "ground almonds", category: "other" },
  { name: "naan", category: "other" },
  { name: "white chocolate", category: "sweets" },
  { name: "white chocolate chips", category: "sweets" },
  { name: "chicken stock pot", category: "other" },
  { name: "coconut oil", category: "other" },
  { name: "sesame seeds", category: "other" },
  { name: "ginger paste", category: "other" },
  { name: "salad", category: "other" },
  { name: "Thai crackers", category: "other" },
  { name: "Chinese five spice", category: "spice" },
  { name: "almond milk", category: "dairy" },
  { name: "baby tomatoes", category: "vegetable" },
  { name: "beansprouts", category: "vegetable" },
  { name: "cucumber", category: "vegetable" },
  { name: "shallots", category: "vegetable" },
  { name: "sun-dried tomato", category: "vegetable" },
  { name: "sweet peppers", category: "vegetable" },
  { name: "tomato", category: "vegetable" },
  { name: "buttermilk", category: "dairy" },
  { name: "cheese", category: "dairy" },
  { name: "coconut cream", category: "oil-fat" },
  { name: "Greek yoghurt", category: "dairy" },
  { name: "light cream cheese", category: "dairy" },
  { name: "yoghurt", category: "dairy" },
  { name: "baps", category: "grain" },
  { name: "basmati rice", category: "grain" },
  { name: "orzo", category: "grain" },
  { name: "pita", category: "grain" },
  { name: "spaghetti", category: "grain" },
  { name: "dried oregano", category: "spice" },
  { name: "basil", category: "herb" },
  { name: "basil leaves", category: "herb" },
  { name: "coriander", category: "herb" },
  { name: "dried rosemary", category: "herb" },
  { name: "dried thyme", category: "herb" },
  { name: "herbes de provence", category: "herb" },
  { name: "chili powder", category: "spice" },
  { name: "garam masala", category: "spice" },
  { name: "ground cumin", category: "spice" },
  { name: "kosher salt", category: "spice" },
  { name: "mustard powder", category: "spice" },
  { name: "onion powder", category: "spice" },
  { name: "pepper", category: "spice" },
  { name: "sweet paprika", category: "spice" },
  { name: "mexican seasoning", category: "spice" },
  { name: "balsamic vinegar", category: "condiment" },
  { name: "chilli mayo", category: "condiment" },
  { name: "crunchy peanut butter", category: "condiment" },
  { name: "ginger puree", category: "condiment" },
  { name: "lemon juice", category: "condiment" },
  { name: "red curry paste", category: "condiment" },
  { name: "sriracha", category: "condiment" },
  { name: "white wine vinegar", category: "condiment" },
  { name: "light brown sugar", category: "sweets" },
  { name: "sesame oil", category: "oil-fat" },
  { name: "chicken thigh", category: "protein" },
  { name: "frozen raspberries", category: "fruit" },
] as const;
