import type { RecipeContent } from "@/lib/domain/recipe/recipe";

export const recipes: RecipeContent[] = [
  {
    title: "Simple Creamy Chicken Curry",
    slug: "creamy-chicken-curry",
    description:
      "A simple mixture of basic spices with cream, chicken and onions",
    date: "2014-01-01",
    tags: [],
    cuisine: "Asian",
    servings: 5,
    prepTime: 15,
    cookTime: 60,
    ingredientGroups: [
      {
        items: [
          {
            ingredient: "chicken-breast",
            amount: 3,
            unit: "piece",
            preparation: "cubed",
          },
          {
            ingredient: "white-onion",
            amount: 2,
            unit: "piece",
            preparation: "cubed",
          },
          { ingredient: "single-cream", amount: 250, unit: "ml" },
          {
            ingredient: "chicken-stock",
            amount: 430,
            unit: "ml",
            note: "double strength",
          },
          { ingredient: "butter", note: "for frying" },
          { ingredient: "rice", amount: 80, unit: "g", note: "per portion" },
        ],
      },
      {
        name: "Spice Mix",
        items: [
          { ingredient: "plain-flour", amount: 4, unit: "tsp" },
          { ingredient: "curry-powder", amount: 2, unit: "tsp" },
          { ingredient: "hot-chilli-powder", amount: 0.5, unit: "tsp" },
          { ingredient: "ground-coriander", amount: 1, unit: "tsp" },
          { ingredient: "cayenne-pepper", amount: 1, unit: "tsp" },
          { ingredient: "paprika", amount: 1, unit: "tsp" },
          { ingredient: "brown-sugar", amount: 1, unit: "tsp" },
        ],
      },
      {
        name: "Extras",
        items: [{ ingredient: "prawn-crackers" }],
      },
    ],
    instructions: [
      "Melt the butter in a saucepan",
      "Fry the onions in the butter until brown",
      "Mix all spice mix ingredients in a large bowl",
      "Mix the chicken in with the spice mix, covering well",
      "Pour the contents of the bowl into the saucepan",
      "Pour in the stock",
      "Simmer the mixture for 30 minutes, then add the cream",
      "Simmer for a further 30 minutes. Boil the rice during this period to be ready",
      "Serve on a bed of rice with a side of prawn crackers",
    ],
  },
  {
    title: "Macaroni Cheese Bake",
    slug: "macaroni-cheese-bake",
    description: "Super cheesy pasta bake",
    date: "2015-07-01",
    tags: [],
    cuisine: "Italian",
    servings: 7,
    prepTime: 10,
    cookTime: 25,
    ingredientGroups: [
      {
        items: [
          { ingredient: "macaroni", amount: 400, unit: "g" },
          { ingredient: "butter", amount: 50, unit: "g" },
          { ingredient: "plain-flour", amount: 50, unit: "g" },
          { ingredient: "milk", amount: 700, unit: "ml" },
          {
            ingredient: "bacon",
            amount: 3,
            unit: "slice",
            preparation: "chopped",
          },
          {
            ingredient: "cheddar-cheese",
            amount: 200,
            unit: "g",
            preparation: "grated",
          },
          {
            ingredient: "parmesan",
            preparation: "grated",
            note: "for topping",
          },
        ],
      },
      {
        name: "Extras",
        items: [{ ingredient: "peri-peri-salt", note: "to top" }],
      },
    ],
    instructions: [
      "Boil the pasta",
      "Fry the bacon",
      "Heat the milk in the microwave",
      "Melt butter in a saucepan",
      "Stir flour into melted butter, cook for 1 minute",
      "Slowly add the milk, stirring constantly",
      "Bring to the boil, then reduce to simmer",
      "Mix in cheddar cheese until melted",
      "Mix in pasta",
      "Transfer to oven dish",
      "Mix in bacon",
      "Sprinkle with Parmesan",
      "Grill until crispy",
    ],
  },
  {
    title: "Chicken & Chorizo Risotto",
    slug: "chicken-chorizo-risotto",
    description: "Tomato based, lightly spicy risotto",
    date: "2015-09-01",
    tags: [],
    cuisine: "Italian",
    servings: 7,
    prepTime: 15,
    cookTime: 35,
    ingredientGroups: [
      {
        items: [
          {
            ingredient: "red-onion",
            amount: 2,
            unit: "piece",
            preparation: "chopped",
          },
          {
            ingredient: "bell-pepper",
            amount: 2,
            unit: "piece",
            preparation: "chopped",
          },
          {
            ingredient: "chicken-breast",
            amount: 3,
            unit: "piece",
            preparation: "cubed",
          },
          {
            ingredient: "chorizo",
            amount: 220,
            unit: "g",
            preparation: "chopped",
          },
          { ingredient: "arborio-rice", amount: 470, unit: "g" },
          { ingredient: "vegetable-stock", amount: 1100, unit: "ml" },
          { ingredient: "tomato-passata", amount: 500, unit: "g" },
          { ingredient: "garlic", amount: 2, unit: "tsp" },
          { ingredient: "chilli", amount: 2, unit: "tsp" },
          { ingredient: "italian-seasoning" },
          {
            ingredient: "cheddar-cheese",
            amount: 1,
            unit: "handful",
            preparation: "grated",
          },
          { ingredient: "black-pepper" },
        ],
      },
      {
        name: "Extras",
        items: [{ ingredient: "garlic-bread" }],
      },
    ],
    instructions: [
      "In a large frying pan, fry the chicken for 3 minutes on a medium heat",
      "Add onions, peppers, garlic and chilli; fry until soft",
      "Fry chorizo in a separate large saucepan until it releases its oils",
      "Add Arborio rice to the saucepan and fry for 2 minutes",
      "Add chicken stock and passata to saucepan and bring to the boil",
      "Reduce to a simmer and add Italian seasoning",
      "Simmer for 25\u201330 minutes, stirring regularly",
      "Serve in a bowl, with self-service black pepper and parmesan cheese; and a side of garlic bread",
    ],
  },
  {
    title: "Marinated Satay Chicken",
    slug: "marinated-satay-chicken",
    description: "Creamy, peanut-based sauce with chicken and rice",
    date: "2016-07-01",
    tags: [],
    cuisine: "Asian",
    servings: 4,
    prepTime: 40,
    cookTime: 25,
    ingredientGroups: [
      {
        items: [
          { ingredient: "chicken-breast", amount: 3, unit: "piece" },
          { ingredient: "soy-sauce", amount: 3, unit: "tbsp" },
          { ingredient: "lime-juice", amount: 4.5, unit: "tbsp" },
          { ingredient: "peanut-butter", amount: 3, unit: "tbsp" },
          { ingredient: "honey", amount: 3, unit: "tbsp" },
          { ingredient: "tikka-curry-powder", amount: 1.5, unit: "tbsp" },
          { ingredient: "garlic", amount: 3, unit: "clove" },
          {
            ingredient: "coconut-milk",
            amount: 400,
            unit: "ml",
            note: "1 tin",
          },
          { ingredient: "rice", amount: 320, unit: "g" },
        ],
      },
    ],
    instructions: [
      "Chop the chicken breasts into strips",
      "Crush the garlic cloves",
      "Mix together: soy sauce, lime juice, peanut butter, honey, curry powder, and crushed garlic cloves",
      "Marinate the chicken strips in the mixture for at least 30 minutes",
      "Bake the marinated chicken strips in the oven for 10\u201315 minutes at 180\u00baC. The chicken will be soft, but ensure it is cooked through",
      "Boil the rice",
      "Mix the coconut milk with the remaining marinade",
      "Boil the marinade mixture until reduced well",
      "Place the rice and chicken on a plate",
      "Pour the reduced satay sauce over the chicken",
    ],
  },
  {
    title: "Creamy Pesto Risotto",
    slug: "creamy-pesto-risotto",
    description: "A rich, decadent risotto",
    date: "2017-08-01",
    tags: [],
    cuisine: "Italian",
    servings: 5,
    prepTime: 10,
    cookTime: 25,
    ingredientGroups: [
      {
        items: [
          { ingredient: "olive-oil", amount: 2, unit: "tbsp" },
          {
            ingredient: "onion",
            amount: 1,
            unit: "piece",
            preparation: "chopped",
            note: "large",
          },
          {
            ingredient: "chicken-breast",
            amount: 1,
            unit: "piece",
            preparation: "cubed",
            note: "large",
          },
          { ingredient: "arborio-rice", amount: 350, unit: "g" },
          { ingredient: "vegetable-stock", amount: 1200, unit: "ml" },
          { ingredient: "peas", amount: 100, unit: "g", note: "defrosted" },
          { ingredient: "basil-pesto", amount: 65, unit: "g" },
          { ingredient: "butter", amount: 35, unit: "g" },
          {
            ingredient: "grana-padano",
            amount: 40,
            unit: "g",
            preparation: "grated",
          },
          { ingredient: "salt" },
          { ingredient: "black-pepper" },
        ],
      },
      {
        name: "Extras",
        items: [{ ingredient: "garlic-bread" }],
      },
    ],
    instructions: [
      "Pour oil into saucepan",
      "Fry onions at medium heat for 4 minutes, stirring occasionally",
      "Add chicken and fry for 2 minutes",
      "Add Arborio rice and fry for 2 minutes",
      "Pour in a couple of ladles of stock and bring to a simmer",
      "Stir until all the stock is absorbed",
      "Add in the peas",
      "Add some stock, stir until absorbed. Repeat until all stock is absorbed (expect to take 15\u201320 minutes)",
      "Stir in butter, pesto and Grana Padano cheese",
      "Season well with salt and pepper",
      "Serve in a bowl, with self-service black pepper and parmesan cheese, and a side of garlic bread",
    ],
  },
  {
    title: "Chilli Chicken Penne Pasta",
    slug: "chilli-chicken-penne-pasta",
    description: "Quick and easy, sweet, spicy and creamy pasta dish",
    date: "2017-10-01",
    tags: [],
    cuisine: "Italian",
    servings: 6,
    prepTime: 10,
    cookTime: 20,
    ingredientGroups: [
      {
        items: [
          {
            ingredient: "chicken-breast",
            amount: 3,
            unit: "piece",
            preparation: "chopped",
          },
          { ingredient: "penne-pasta" },
          {
            ingredient: "red-pepper",
            amount: 1,
            unit: "piece",
            preparation: "chopped",
          },
          { ingredient: "garlic", amount: 1, unit: "tsp" },
          { ingredient: "chilli", amount: 1, unit: "tsp" },
          { ingredient: "creme-fraiche", amount: 300, unit: "ml" },
          { ingredient: "sweet-chilli-sauce", amount: 12, unit: "tbsp" },
          { ingredient: "smoked-paprika" },
          { ingredient: "black-pepper" },
        ],
      },
      {
        name: "Extras",
        items: [{ ingredient: "garlic-bread" }],
      },
    ],
    instructions: [
      "Start boiling the pasta. Preheat oven if having garlic bread",
      "Fry the chicken for a few minutes",
      "Add the pepper, garlic and chilli; cook until chicken is browned. Add garlic bread to oven",
      "Reduce to low heat",
      "Add sweet chilli sauce",
      "Add creme fraiche, a few tablespoons at a time, until you achieve the desired taste",
      "Simmer for one minute",
      "Add smoked paprika and black pepper to taste",
      "Stir cooked pasta through sauce",
      "Serve on a plate, with self-service black pepper and parmesan cheese; and a side of garlic bread",
    ],
  },
  {
    title: "Turkey Pasta Bake",
    slug: "turkey-pasta-bake",
    description: "Lightly spicy, tomato and cream based turkey pasta bake",
    date: "2020-05-01",
    tags: [],
    cuisine: "Italian",
    servings: 7,
    prepTime: 15,
    cookTime: 35,
    ingredientGroups: [
      {
        items: [
          { ingredient: "large-pasta-shells", amount: 400, unit: "g" },
          { ingredient: "turkey-mince", amount: 500, unit: "g" },
          {
            ingredient: "white-onion",
            amount: 1,
            unit: "piece",
            preparation: "chopped",
          },
          {
            ingredient: "garlic",
            amount: 3,
            unit: "clove",
            preparation: "crushed",
          },
          { ingredient: "chopped-tomatoes", amount: 1, unit: "tin" },
          { ingredient: "chicken-stock", amount: 1, unit: "cube" },
          { ingredient: "mascarpone", amount: 250, unit: "g" },
          {
            ingredient: "cheddar-cheese",
            amount: 200,
            unit: "g",
            preparation: "grated",
          },
          { ingredient: "chipotle-paste", amount: 1, unit: "tbsp" },
          {
            ingredient: "parmesan",
            amount: 1,
            unit: "handful",
            preparation: "grated",
          },
          { ingredient: "black-pepper" },
          { ingredient: "oregano" },
        ],
      },
    ],
    instructions: [
      "Start boiling the pasta",
      "Fry the onion until soft",
      "Add the turkey mince, and fry until brown all over",
      "Add the garlic, chopped tomatoes, chipotle paste and chicken stock cube",
      "Bring mixture to the boil, then reduce to a simmer",
      "Once pasta is cooked, drain it, retaining some pasta water",
      "Mix the mascarpone into the pasta water at a low heat",
      "Add 140g of cheddar to the mascarpone sauce. Season well with black pepper and oregano",
      "Add pasta to cheese sauce and mix",
      "Add the turkey mixture to an oven dish",
      "Pour the pasta and cheese sauce on top of the turkey mixture",
      "Sprinkle remaining cheddar and parmesan on top",
      "Bake in the oven for 20 minutes at 200\u00b0C or until golden",
    ],
  },
  {
    title: "Sausage Jambalaya",
    slug: "sausage-jambalaya",
    description:
      "A hearty Cajun-spiced one-pot rice dish with sausages and vegetables",
    date: "2024-02-11",
    tags: ["one-pot"],
    cuisine: "Cajun",
    servings: 4,
    prepTime: 10,
    cookTime: 25,
    ingredientGroups: [
      {
        items: [
          { ingredient: "olive-oil", amount: 1, unit: "tbsp" },
          {
            ingredient: "pork-sausages",
            amount: 8,
            unit: "piece",
            preparation: "cut into pieces",
          },
          { ingredient: "cajun-seasoning", amount: 1.5, unit: "tbsp" },
          {
            ingredient: "white-onion",
            amount: 1,
            unit: "piece",
            preparation: "finely chopped",
          },
          { ingredient: "long-grain-rice", amount: 200, unit: "g" },
          {
            ingredient: "chopped-tomatoes",
            amount: 1,
            unit: "tin",
            note: "400g",
          },
          { ingredient: "water", amount: 400, unit: "ml" },
          {
            ingredient: "frozen-vegetables",
            amount: 150,
            unit: "g",
            note: "peas and peppers",
          },
          { ingredient: "chilli", note: "optional, to taste" },
          { ingredient: "garlic", note: "optional, to taste" },
          { ingredient: "paprika", note: "optional, to taste" },
          { ingredient: "salt", note: "to taste" },
          { ingredient: "black-pepper", note: "to taste" },
        ],
      },
    ],
    instructions: [
      "Put the rice in a sieve and rinse thoroughly",
      "Heat the oil in a large pan and brown the sausages for a few minutes",
      "Stir in the Cajun seasoning and onion; cook for 2 minutes",
      "Add the rice and cook for 30 seconds, then pour in the chopped tomatoes and 400ml water",
      "Bring to the boil, lower the heat and add optional herbs and spices (chilli, garlic, paprika) to taste",
      "Cover with a lid and simmer for 10 minutes",
      "Stir in frozen vegetables and cook for another 10 minutes",
      "Season with salt and pepper to taste",
    ],
  },
  {
    title: "Cajun Sausage Pasta",
    slug: "cajun-sausage-pasta",
    description:
      "A hearty and creamy pasta dish with spicy Cajun sausage, fresh tomatoes, and a cheesy sauce.",
    date: "2025-11-01",
    tags: ["creamy"],
    cuisine: "Cajun",
    servings: 4,
    prepTime: 10,
    cookTime: 20,
    ingredientGroups: [
      {
        items: [
          { ingredient: "pasta", amount: 320, unit: "g" },
          {
            ingredient: "pork-sausages",
            amount: 6,
            unit: "piece",
            preparation: "deskinned",
            note: "Tesco finest work best",
          },
          {
            ingredient: "red-onion",
            amount: 1,
            unit: "piece",
            preparation: "finely chopped",
            note: "1 large or 2 small",
          },
          { ingredient: "cajun-seasoning", amount: 4, unit: "tsp" },
          { ingredient: "smoked-paprika", amount: 2, unit: "tsp" },
          { ingredient: "dried-parsley", amount: 4, unit: "tsp" },
          { ingredient: "garlic-puree", amount: 4, unit: "tsp" },
          {
            ingredient: "fresh-tomatoes",
            amount: 4,
            unit: "piece",
            preparation: "diced",
          },
          { ingredient: "tomato-puree", amount: 2, unit: "tbsp" },
          {
            ingredient: "cheddar-cheese",
            amount: 80,
            unit: "g",
            preparation: "grated",
          },
          { ingredient: "cream-cheese", amount: 4, unit: "tbsp" },
          { ingredient: "black-pepper", note: "to season" },
          { ingredient: "olive-oil", note: "for frying" },
        ],
      },
    ],
    instructions: [
      "Cook pasta according to package instructions, ensuring to save a few ladles of pasta water before draining.",
      "While pasta is cooking, heat some oil in a separate pan on medium heat.",
      "Add the deskinned sausages, red onion, cajun seasoning and paprika and cook for 5 minutes, breaking up the sausages as they cook.",
      "Add in the garlic puree, dried parsley, tomatoes and tomato puree and cook for a few more minutes.",
      "Stir in cream cheese and some pasta water. Add a little at a time to get desired consistency.",
      "Bring to a simmer.",
      "Add in grated cheese and cooked pasta ensuring it's all coated and melted.",
      "Season with black pepper.",
    ],
  },
];
