{ config, lib, pkgs, ... }:

{
  # hardware-configuration.nix is generated by nixos-generate-config at install
  # time and is machine-specific, so import it only when it exists.
  imports = lib.optional (builtins.pathExists ./hardware-configuration.nix) ./hardware-configuration.nix;

  nixpkgs.config.allowUnfree = true;

  environment.systemPackages = with pkgs; [
    git curl htop ripgrep vim tailscale
  ];

  # GTX 1060 (Pascal) needs the 580 driver branch, which is the last to
  # support Pascal. Pin an LTS kernel the 580 drivers support.
  boot.kernelPackages = pkgs.linuxPackages_6_12;

  hardware.graphics.enable = true;
  hardware.nvidia.enable = true;
  hardware.nvidia.open = false;
  # nvidiaPackages.stable must still be a 580.x; if it drifts past 580, pin the
  # last 580 build explicitly via nvidiaPackages.mkDriver.
  hardware.nvidia.package = config.boot.kernelPackages.nvidiaPackages.stable;

  # GPU access inside Docker (models are run via nvidia/cuda:12.x images,
  # never 13.x — CUDA 13 dropped Pascal).
  hardware.nvidia-container-toolkit.enable = true;
  virtualisation.docker.enable = true;
  virtualisation.docker.autoPrune.enable = true;

  users.users.robbie = {
    isNormalUser = true;
    extraGroups = [ "docker" "wheel" ];
    openssh.authorizedKeys.keys = [
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIM10tppAS+3nlXzecNqk+YUuzwN2KtT5//gwoUqhDt36 robbiepalmer@live.co.uk"
    ];
  };

  networking.hostName = "asus-desktop";

  services.tailscale.enable = true;
  networking.firewall.trustedInterfaces = [ "tailscale0" ];
  services.openssh.enable = true;

  # Wake-on-LAN so the box can sleep and be roused on demand. Confirm the real
  # interface name with `ip link` and enable WOL in the BIOS too.
  networking.interfaces.eth0.wakeOnLan = true;
  powerManagement.enable = true;

  system.stateVersion = "25.11";
}
