name: Lint CI

on:
  pull_request:
    paths:
      - "**/*.md"
      - "**/*.yml"
      - "**/*.yaml"
      - ".github/workflows/lint-ci.yml"
      - ".mise.toml"
      - ".markdownlint.json"
      - ".yamllint"
      - "package.json"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0
        with:
          experimental: true

      - name: Get pnpm store directory
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> "$GITHUB_ENV"

      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ${{ env.STORE_PATH }}
          key: pnpm-store-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: pnpm-store-${{ runner.os }}-

      - name: Install dependencies
        run: mise run //:install

      - name: Lint Markdown files
        run: mise run //:lint:markdown:check

      - name: Lint YAML files
        run: mise run //:lint:yaml
