name: TFLint CI

on:
  pull_request:
    paths:
      - "**/*.tf"
      - "**/.tflint.hcl"
      - ".mise.toml"
      - ".github/workflows/tflint-ci.yml"

permissions: {}

jobs:
  tflint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4.3.0
        with:
          experimental: true

      - name: Lint public platform infrastructure with TFLint
        run: mise run //infra/public-platform:lint:tflint

      - name: Lint bootstrap infrastructure with TFLint
        run: mise run //infra/bootstrap:lint:tflint
